// GENERATED by scripts/pbyp-refresh-schema.ts — do not edit by hand.
// Source: https://directus.preprod.pbyp.fr · 91 collections · 845 fields.
//
// Regenerate after any Pbyp schema change:
//   PBYP_DIRECTUS_URL=… PBYP_ADMIN_TOKEN=… bun run scripts/pbyp-refresh-schema.ts

import type { PbypSchema } from "./schema-types";

export const PBYP_SCHEMA: PbypSchema = {
  address: {
    primaryKey: "id",
    fields: {
      access_entities: {
        type: "alias",
        readonly: true,
        relation: {
          kind: "m2m",
          through: "address_entities",
          fk: "address_id",
          otherFk: "entities_id",
          to: "entities",
        },
      },
      address: {
        type: "string",
      },
      address_book: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "address_book",
        },
      },
      city: {
        type: "string",
      },
      code: {
        type: "string",
        required: true,
      },
      complement: {
        type: "string",
      },
      coordinates: {
        type: "geometry.Point",
      },
      country_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "countries",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      edicode: {
        type: "string",
      },
      email: {
        type: "string",
      },
      id: {
        type: "integer",
        readonly: true,
      },
      instruction: {
        type: "string",
      },
      is_hayon: {
        type: "boolean",
      },
      locality_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "localities",
        },
      },
      mapbox_id: {
        type: "string",
      },
      max_time: {
        type: "string",
      },
      name: {
        type: "string",
        required: true,
      },
      phone: {
        type: "string",
      },
      to_delete: {
        type: "boolean",
      },
      zipcode: {
        type: "string",
      },
    },
  },
  address_book: {
    primaryKey: "id",
    fields: {
      address: {
        type: "string",
      },
      associated_entities: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "address_book_entities",
          fk: "address_book_id",
          otherFk: "entities_id",
          to: "entities",
        },
      },
      city: {
        type: "string",
      },
      code: {
        type: "string",
        required: true,
      },
      complement: {
        type: "string",
      },
      coordinates: {
        type: "geometry.Point",
      },
      country_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "countries",
        },
      },
      date_created: {
        type: "timestamp",
      },
      date_updated: {
        type: "timestamp",
      },
      email: {
        type: "string",
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
      },
      instruction: {
        type: "string",
      },
      is_hayon: {
        type: "boolean",
      },
      locality_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "localities",
        },
      },
      mapbox_id: {
        type: "string",
      },
      max_time: {
        type: "string",
      },
      name: {
        type: "string",
        required: true,
      },
      phone: {
        type: "string",
      },
      zipcode: {
        type: "string",
      },
    },
  },
  address_book_entities: {
    primaryKey: "id",
    fields: {
      address_book_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "address_book",
        },
      },
      can_edit: {
        type: "boolean",
      },
      entities_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
      },
    },
  },
  address_entities: {
    primaryKey: "id",
    fields: {
      address_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      entities_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
      },
    },
  },
  adr: {
    primaryKey: "id",
    fields: {
      class: {
        type: "string",
        required: true,
      },
      classification: {
        type: "string",
        required: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      libel_fr: {
        type: "string",
        required: true,
      },
      un_code: {
        type: "string",
        required: true,
      },
    },
  },
  ai_form_configs: {
    primaryKey: "id",
    fields: {
      ai_workflow: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "ai_workflows",
        },
      },
      client: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
      system_prompt: {
        type: "text",
        required: true,
      },
    },
  },
  ai_ocrs: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      entity: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      order: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "orders",
        },
      },
      user_created: {
        type: "uuid",
        required: true,
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  ai_prompts: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      description: {
        type: "text",
      },
      id: {
        type: "uuid",
      },
      messages: {
        type: "json",
      },
      meta_prompts_notice: {
        type: "alias",
      },
      name: {
        type: "string",
        required: true,
      },
      sort: {
        type: "integer",
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      system_prompt: {
        type: "text",
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  ai_workflows: {
    primaryKey: "id",
    fields: {
      code: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      default_system_prompt: {
        type: "text",
        required: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
      path: {
        type: "string",
        required: true,
      },
    },
  },
  air_bookings: {
    primaryKey: "id",
    fields: {
      agent_code: {
        type: "string",
      },
      airline_company: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "oversea_companies",
        },
      },
      arrival_terminal: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "terminals",
        },
      },
      ATA: {
        type: "timestamp",
      },
      ATD: {
        type: "timestamp",
      },
      booking_number: {
        type: "string",
      },
      booking_type: {
        type: "string",
        required: true,
        choices: ["import", "export"],
      },
      co2: {
        type: "float",
      },
      co2_factor: {
        type: "float",
      },
      custom_company: {
        type: "string",
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      departure_terminal: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "terminals",
        },
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      ETA: {
        type: "timestamp",
        required: true,
      },
      ETD: {
        type: "timestamp",
        required: true,
      },
      events: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "air_bookings_events",
          fk: "air_bookings_id",
          otherFk: "events_id",
          to: "events",
        },
      },
      flights: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "air_bookings_flights",
          fk: "booking",
        },
      },
      folders: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "air_folders",
          fk: "voyage_id",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      LTA: {
        type: "string",
        required: true,
      },
      new_ETA: {
        type: "dateTime",
      },
      new_ETD: {
        type: "dateTime",
      },
      old_LTA: {
        type: "string",
      },
      shipping_status: {
        type: "string",
        required: true,
        choices: ["CANCELED", "CREATED", "IN_TRANSIT", "ARRIVED_AT_POL"],
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      tracking_id: {
        type: "string",
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      voyage_number: {
        type: "string",
      },
    },
  },
  air_bookings_events: {
    primaryKey: "id",
    fields: {
      air_bookings_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "air_bookings",
        },
      },
      events_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "events",
        },
      },
      id: {
        type: "integer",
      },
    },
  },
  air_bookings_flights: {
    primaryKey: "id",
    fields: {
      booking: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "air_bookings",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      eta: {
        type: "timestamp",
        required: true,
      },
      etd: {
        type: "timestamp",
        required: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      number: {
        type: "string",
      },
      pod: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "terminals",
        },
      },
      pol: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "terminals",
        },
      },
    },
  },
  air_bookings_lta: {
    primaryKey: "id",
    fields: {
      airline_company: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "oversea_companies",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      is_used: {
        type: "boolean",
      },
      lta: {
        type: "string",
        required: true,
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
    },
  },
  air_folders: {
    primaryKey: "id",
    fields: {
      billing_reference: {
        type: "string",
      },
      client_reference: {
        type: "string",
      },
      co2: {
        type: "float",
      },
      comments: {
        type: "text",
      },
      consignee: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      date: {
        type: "date",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      delivery_date: {
        type: "timestamp",
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      events: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "air_folders_events",
          fk: "air_folders_id",
          otherFk: "events_id",
          to: "events",
        },
      },
      external_references: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "external_references",
          fk: "air_folder",
        },
      },
      files: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "air_folders_files",
          fk: "air_folders_id",
          otherFk: "files_id",
          to: "files",
        },
      },
      folder_number: {
        type: "string",
        required: true,
        readonly: true,
      },
      folder_type: {
        type: "string",
        required: true,
        choices: ["single", "master", "house"],
      },
      folders_entities: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "air_folders_entities",
          fk: "air_folders_id",
          otherFk: "entities_id",
          to: "entities",
        },
      },
      houses: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "air_folders",
          fk: "master_id",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      incoterm: {
        type: "string",
        required: true,
        choices: ["EXW", "FCA", "CPT", "CIP", "DAP", "DPU", "DDP"],
      },
      main_external_reference: {
        type: "string",
      },
      master_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "air_folders",
        },
      },
      orders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "air_folders_orders",
          fk: "air_folders_id",
          otherFk: "orders_id",
          to: "orders",
        },
      },
      parcels: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "air_folders_parcels",
          fk: "air_folders_id",
          otherFk: "parcels_id",
          to: "parcels",
        },
      },
      parcels_description: {
        type: "text",
      },
      parcels_link_type: {
        type: "string",
        choices: ["folder", "order"],
      },
      parcels_price: {
        type: "float",
      },
      parcels_price_currency: {
        type: "string",
        choices: ["EUR", "USD"],
      },
      payer_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      pickup_date: {
        type: "timestamp",
      },
      shipper: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      shipping_status: {
        type: "string",
        required: true,
        choices: [
          "CANCELED",
          "CREATED",
          "PICKED_UP",
          "ARRIVED_AT_POL",
          "IN_TRANSIT",
          "ARRIVED_AT_POD",
          "DELIVERED",
        ],
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      total_meterage: {
        type: "float",
      },
      total_quantity: {
        type: "integer",
      },
      total_taxable_weight: {
        type: "float",
      },
      total_volume: {
        type: "float",
      },
      total_weight: {
        type: "float",
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      voyage_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "air_bookings",
        },
      },
    },
  },
  air_folders_entities: {
    primaryKey: "id",
    fields: {
      air_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "air_folders",
        },
      },
      can_edit: {
        type: "boolean",
      },
      entities_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
      },
    },
  },
  air_folders_events: {
    primaryKey: "id",
    fields: {
      air_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "air_folders",
        },
      },
      events_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "events",
        },
      },
      id: {
        type: "integer",
      },
    },
  },
  air_folders_files: {
    primaryKey: "id",
    fields: {
      air_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "air_folders",
        },
      },
      files_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "files",
        },
      },
      id: {
        type: "integer",
      },
    },
  },
  air_folders_orders: {
    primaryKey: "id",
    fields: {
      air_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "air_folders",
        },
      },
      id: {
        type: "integer",
      },
      orders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "orders",
        },
      },
    },
  },
  air_folders_parcels: {
    primaryKey: "id",
    fields: {
      air_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "air_folders",
        },
      },
      id: {
        type: "integer",
      },
      parcels_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "parcels",
        },
      },
    },
  },
  alerts: {
    primaryKey: "id",
    fields: {
      data: {
        type: "json",
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      external_email: {
        type: "string",
      },
      id: {
        type: "integer",
        readonly: true,
      },
      is_send: {
        type: "boolean",
        readonly: true,
      },
      item_code: {
        type: "string",
      },
      type: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "type_alerts",
        },
      },
      user: {
        type: "uuid",
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  associated_entities: {
    primaryKey: "id",
    fields: {
      entities_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
      },
      related_entities_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
    },
  },
  booking_edi: {
    primaryKey: "id",
    fields: {
      air_booking_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "air_bookings",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      gateway_external_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "gateway_external",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      is_pbyp_export: {
        type: "boolean",
      },
      is_updated: {
        type: "boolean",
      },
      receive_validation: {
        type: "boolean",
      },
      sea_booking_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_bookings",
        },
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  container_seals: {
    primaryKey: "id",
    fields: {
      container: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "containers",
        },
      },
      date: {
        type: "dateTime",
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      number: {
        type: "string",
        required: true,
      },
    },
  },
  containers: {
    primaryKey: "id",
    fields: {
      co2: {
        type: "float",
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      events: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "containers_events",
          fk: "containers_id",
          otherFk: "events_id",
          to: "events",
        },
      },
      folders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_folders_containers",
          fk: "containers_id",
          otherFk: "sea_folders_id",
          to: "sea_folders",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      number: {
        type: "string",
        required: true,
      },
      orders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "orders_containers",
          fk: "containers_id",
          otherFk: "orders_id",
          to: "orders",
        },
      },
      parcels: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "parcels",
          fk: "container",
        },
      },
      sea_booking: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "sea_bookings",
        },
      },
      seals: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "container_seals",
          fk: "container",
        },
      },
      shipping_method: {
        type: "string",
        choices: ["FCL/FCL", "FCL/LCL", "LCL/LCL", "LCL/FCL", "RORO"],
      },
      shipping_status: {
        type: "string",
        required: true,
        choices: [
          "CANCELED",
          "CREATED",
          "ARRIVED_AT_POL",
          "LOADED",
          "IN_TRANSIT",
          "ARRIVED_AT_POD",
          "DISCHARGED",
        ],
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      type: {
        type: "string",
        required: true,
        choices: [
          "10D",
          "10HC",
          "20D",
          "20HC",
          "20R",
          "40D",
          "40HC",
          "40R",
          "45",
          "20OT",
          "40OT",
          "20FR",
          "40FR",
        ],
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  containers_events: {
    primaryKey: "id",
    fields: {
      containers_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "containers",
        },
      },
      events_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "events",
        },
      },
      id: {
        type: "integer",
      },
    },
  },
  countries: {
    primaryKey: "id",
    fields: {
      code2: {
        type: "string",
        required: true,
      },
      code3: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      english_name: {
        type: "string",
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
      number: {
        type: "string",
        required: true,
      },
    },
  },
  currencies: {
    primaryKey: "id",
    fields: {
      code: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "dateTime",
      },
      id: {
        type: "integer",
        readonly: true,
      },
      symbol: {
        type: "string",
        required: true,
      },
      usd_value: {
        type: "decimal",
      },
    },
  },
  customers: {
    primaryKey: "id",
    fields: {
      client: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      department: {
        type: "string",
      },
      email: {
        type: "string",
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      first_name: {
        type: "string",
        required: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      last_name: {
        type: "string",
        required: true,
      },
      locality: {
        type: "string",
      },
      phone: {
        type: "string",
      },
      role: {
        type: "string",
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  entities: {
    primaryKey: "id",
    fields: {
      address_book: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "address_book",
        },
      },
      associated_entities: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "associated_entities",
          fk: "entities_id",
          otherFk: "related_entities_id",
          to: "entities",
        },
      },
      association_key: {
        type: "string",
      },
      children: {
        type: "alias",
        readonly: true,
        relation: {
          kind: "o2m",
          to: "entities",
          fk: "parent_id",
        },
      },
      clients: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "entities_clients",
          fk: "entities_id",
          otherFk: "client_id",
          to: "entities",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      default_currency: {
        type: "string",
      },
      entity_type_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entity_types",
        },
      },
      freight_forwarders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "entities_clients",
          fk: "client_id",
          otherFk: "entities_id",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      is_client: {
        type: "boolean",
        required: true,
      },
      logo: {
        type: "uuid",
        relation: {
          kind: "m2o",
          to: "directus_files",
        },
      },
      name: {
        type: "string",
        required: true,
      },
      parent_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
    },
  },
  entities_alerts: {
    primaryKey: "id",
    fields: {
      condition: {
        type: "json",
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      enable: {
        type: "boolean",
        required: true,
      },
      entities: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      type: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "type_alerts",
        },
      },
    },
  },
  entities_clients: {
    primaryKey: "id",
    fields: {
      client_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      commercial: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "customers",
        },
      },
      entities_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
      },
    },
  },
  entity_types: {
    primaryKey: "id",
    fields: {
      code: {
        type: "string",
        required: true,
      },
      color: {
        type: "string",
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      hierarchy: {
        type: "integer",
        required: true,
      },
      icon: {
        type: "string",
        required: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
    },
  },
  event_edi: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      event_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "events",
        },
      },
      external_reference: {
        type: "string",
      },
      gateway_external_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "gateway_external",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      is_pbyp_export: {
        type: "boolean",
      },
      is_updated: {
        type: "boolean",
      },
      receive_validation: {
        type: "boolean",
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  event_types: {
    primaryKey: "id",
    fields: {
      category: {
        type: "json",
        required: true,
        choices: ["booking", "container", "folder", "order"],
      },
      code: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      description: {
        type: "json",
        required: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      modules: {
        type: "json",
        required: true,
        choices: ["sea", "air"],
      },
    },
  },
  events: {
    primaryKey: "id",
    fields: {
      actual: {
        type: "boolean",
        required: true,
      },
      address: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      air_bookings: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "air_bookings_events",
          fk: "events_id",
          otherFk: "air_bookings_id",
          to: "air_bookings",
        },
      },
      air_folders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "air_folders_events",
          fk: "events_id",
          otherFk: "air_folders_id",
          to: "air_folders",
        },
      },
      code: {
        type: "string",
        required: true,
        readonly: true,
      },
      comments: {
        type: "text",
      },
      containers: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "containers_events",
          fk: "events_id",
          otherFk: "containers_id",
          to: "containers",
        },
      },
      date: {
        type: "timestamp",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      "divider-7ssrn1": {
        type: "alias",
      },
      id: {
        type: "integer",
        readonly: true,
      },
      orders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "orders_events",
          fk: "events_id",
          otherFk: "orders_id",
          to: "orders",
        },
      },
      sea_bookings: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_bookings_events",
          fk: "events_id",
          otherFk: "sea_bookings_id",
          to: "sea_bookings",
        },
      },
      sea_folders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_folders_events",
          fk: "events_id",
          otherFk: "sea_folders_id",
          to: "sea_folders",
        },
      },
      source: {
        type: "string",
        required: true,
        readonly: true,
        choices: ["user", "tracking", "ptd"],
      },
      terminal: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "terminals",
        },
      },
      type: {
        type: "integer",
        required: true,
        readonly: true,
        relation: {
          kind: "m2o",
          to: "event_types",
        },
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  external_alerts: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      email: {
        type: "string",
        required: true,
      },
      entity: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      type: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "type_alerts",
        },
      },
    },
  },
  external_event_code: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      event_type: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "event_types",
        },
      },
      external_code: {
        type: "string",
      },
      external_reference_type: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "external_reference_types",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
    },
  },
  external_reference_address: {
    primaryKey: "id",
    fields: {
      address_book: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address_book",
        },
      },
      address_code: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      external_code: {
        type: "string",
        required: true,
      },
      external_reference_types_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "external_reference_types",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
    },
  },
  external_reference_companies: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      external_code: {
        type: "string",
      },
      external_reference_types_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "external_reference_types",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      oversea_company_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "oversea_companies",
        },
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
    },
  },
  external_reference_terminals: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      external_code: {
        type: "string",
        required: true,
      },
      external_references_types: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "external_reference_types",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      terminals_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "terminals",
        },
      },
      type: {
        type: "string",
        required: true,
      },
    },
  },
  external_reference_types: {
    primaryKey: "id",
    fields: {
      code: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
    },
  },
  external_references: {
    primaryKey: "id",
    fields: {
      air_folder: {
        type: "integer",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "air_folders",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      is_main: {
        type: "boolean",
        required: true,
      },
      order: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "orders",
        },
      },
      reference: {
        type: "string",
        required: true,
      },
      sea_folder: {
        type: "integer",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "sea_folders",
        },
      },
      type: {
        type: "integer",
        required: true,
        readonly: true,
        relation: {
          kind: "m2o",
          to: "external_reference_types",
        },
      },
    },
  },
  files: {
    primaryKey: "id",
    fields: {
      access_entity: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "files_entities",
          fk: "files_id",
          otherFk: "entities_id",
          to: "entities",
        },
      },
      agency_owner: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      file: {
        type: "uuid",
        required: true,
        relation: {
          kind: "m2o",
          to: "directus_files",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      tags: {
        type: "string",
      },
    },
  },
  files_entities: {
    primaryKey: "id",
    fields: {
      entities_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      files_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "files",
        },
      },
      id: {
        type: "integer",
      },
    },
  },
  files_type: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      label: {
        type: "string",
      },
      mode: {
        type: "json",
        choices: ["sea", "air"],
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      type: {
        type: "string",
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  folder_edi: {
    primaryKey: "id",
    fields: {
      air_folder_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "air_folders",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      gateway_external_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "gateway_external",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      is_pbyp_export: {
        type: "boolean",
      },
      is_updated: {
        type: "boolean",
      },
      receive_validation: {
        type: "boolean",
      },
      sea_folder_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_folders",
        },
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  gateway_external: {
    primaryKey: "id",
    fields: {
      access_key: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      external_code: {
        type: "string",
        required: true,
      },
      gateway_type: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "external_reference_types",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      user: {
        type: "uuid",
        required: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  languages: {
    primaryKey: "code",
    fields: {
      code: {
        type: "string",
      },
      direction: {
        type: "string",
        choices: ["ltr", "rtl"],
      },
      name: {
        type: "string",
      },
    },
  },
  localities: {
    primaryKey: "id",
    fields: {
      city: {
        type: "string",
      },
      coordinates: {
        type: "geometry.Point",
      },
      country_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "countries",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      department: {
        type: "string",
      },
      full_zip_code: {
        type: "string",
      },
      id: {
        type: "integer",
        readonly: true,
      },
      insee_code: {
        type: "string",
      },
      region_code: {
        type: "string",
      },
      zip_code: {
        type: "string",
      },
    },
  },
  ocr_file_configs: {
    primaryKey: "id",
    fields: {
      client: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      config: {
        type: "json",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      file: {
        type: "uuid",
        required: true,
        relation: {
          kind: "m2o",
          to: "directus_files",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  orders: {
    primaryKey: "id",
    fields: {
      ai_ocr: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "ai_ocrs",
          fk: "order",
        },
      },
      air_folders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "air_folders_orders",
          fk: "orders_id",
          otherFk: "air_folders_id",
          to: "air_folders",
        },
      },
      associated_entities: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "orders_entities",
          fk: "orders_id",
          otherFk: "entities_id",
          to: "entities",
        },
      },
      available_date: {
        type: "date",
      },
      billing_reference: {
        type: "string",
      },
      client_reference: {
        type: "string",
      },
      co2: {
        type: "float",
      },
      comments: {
        type: "text",
      },
      consignee: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      container_link_type: {
        type: "string",
        choices: ["full", "dispatched"],
      },
      containers: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "orders_containers",
          fk: "orders_id",
          otherFk: "containers_id",
          to: "containers",
        },
      },
      date: {
        type: "date",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      deadline: {
        type: "dateTime",
      },
      delivery_date: {
        type: "date",
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      events: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "orders_events",
          fk: "orders_id",
          otherFk: "events_id",
          to: "events",
        },
      },
      external_references: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "external_references",
          fk: "order",
        },
      },
      files: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "orders_files",
          fk: "orders_id",
          otherFk: "files_id",
          to: "files",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      incoterm: {
        type: "string",
        required: true,
        choices: [
          "EXW",
          "FCA",
          "FAS",
          "FOB",
          "CFR",
          "CIF",
          "CPT",
          "CIP",
          "DAP",
          "DPU",
          "DDP",
        ],
      },
      main_external_reference: {
        type: "string",
      },
      number: {
        type: "string",
        required: true,
      },
      parcels: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "orders_parcels",
          fk: "orders_id",
          otherFk: "parcels_id",
          to: "parcels",
        },
      },
      parcels_description: {
        type: "text",
      },
      parcels_price: {
        type: "float",
      },
      parcels_price_currency: {
        type: "string",
        choices: ["EUR", "USD"],
      },
      pickup_date: {
        type: "dateTime",
      },
      sea_folders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_folders_orders",
          fk: "orders_id",
          otherFk: "sea_folders_id",
          to: "sea_folders",
        },
      },
      shipper: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      shipping_status: {
        type: "string",
        required: true,
        choices: [
          "CANCELED",
          "CREATED",
          "PICKED_UP",
          "ARRIVED_AT_POL",
          "IN_TRANSIT",
          "ARRIVED_AT_POD",
          "DELIVERED",
        ],
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      total_meterage: {
        type: "float",
      },
      total_quantity: {
        type: "integer",
      },
      total_taxable_weight: {
        type: "float",
      },
      total_volume: {
        type: "float",
      },
      total_weight: {
        type: "float",
      },
      transport_type: {
        type: "string",
        choices: ["sea", "air"],
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  orders_containers: {
    primaryKey: "id",
    fields: {
      containers_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "containers",
        },
      },
      id: {
        type: "integer",
      },
      orders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "orders",
        },
      },
    },
  },
  orders_edi: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      gateway_external_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "gateway_external",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      is_pbyp_export: {
        type: "boolean",
      },
      is_updated: {
        type: "boolean",
      },
      order_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "orders",
        },
      },
      receive_validation: {
        type: "boolean",
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  orders_entities: {
    primaryKey: "id",
    fields: {
      can_edit: {
        type: "boolean",
      },
      entities_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
      },
      orders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "orders",
        },
      },
    },
  },
  orders_events: {
    primaryKey: "id",
    fields: {
      events_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "events",
        },
      },
      id: {
        type: "integer",
      },
      orders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "orders",
        },
      },
    },
  },
  orders_files: {
    primaryKey: "id",
    fields: {
      files_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "files",
        },
      },
      id: {
        type: "integer",
      },
      orders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "orders",
        },
      },
    },
  },
  orders_parcels: {
    primaryKey: "id",
    fields: {
      id: {
        type: "integer",
      },
      orders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "orders",
        },
      },
      parcels_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "parcels",
        },
      },
    },
  },
  oversea_companies: {
    primaryKey: "id",
    fields: {
      code: {
        type: "string",
        required: true,
      },
      code_iata: {
        type: "string",
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
      prefix: {
        type: "string",
      },
      status: {
        type: "string",
        choices: ["Published", "Draft", "Archived"],
      },
      type: {
        type: "string",
        required: true,
        choices: ["air", "sea"],
      },
      website_host: {
        type: "string",
      },
    },
  },
  parcel_bar_codes: {
    primaryKey: "id",
    fields: {
      bar_code: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "bigInteger",
        readonly: true,
      },
      parcel_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "parcels",
        },
      },
    },
  },
  parcel_types: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
    },
  },
  parcels: {
    primaryKey: "id",
    fields: {
      adr: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "parcels_adr",
          fk: "parcels_id",
          otherFk: "adr_id",
          to: "adr",
        },
      },
      air_folders: {
        type: "alias",
        readonly: true,
        relation: {
          kind: "m2m",
          through: "air_folders_parcels",
          fk: "parcels_id",
          otherFk: "air_folders_id",
          to: "air_folders",
        },
      },
      container: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "containers",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      description: {
        type: "string",
      },
      id: {
        type: "integer",
        readonly: true,
      },
      is_adr: {
        type: "boolean",
      },
      is_controlled_temperature: {
        type: "boolean",
      },
      maximal_temperature: {
        type: "float",
      },
      meterage: {
        type: "float",
        required: true,
      },
      minimal_temperature: {
        type: "float",
      },
      orders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "orders_parcels",
          fk: "parcels_id",
          otherFk: "orders_id",
          to: "orders",
        },
      },
      quantity: {
        type: "integer",
        required: true,
      },
      quotation_orders: {
        type: "alias",
        readonly: true,
        relation: {
          kind: "m2m",
          through: "quotations_orders_parcels",
          fk: "parcels_id",
          otherFk: "quotations_orders_id",
          to: "quotations_orders",
        },
      },
      quotations: {
        type: "alias",
        readonly: true,
        relation: {
          kind: "m2m",
          through: "quotations_parcels",
          fk: "parcels_id",
          otherFk: "quotations_id",
          to: "quotations",
        },
      },
      sea_folders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_folders_parcels",
          fk: "parcels_id",
          otherFk: "sea_folders_id",
          to: "sea_folders",
        },
      },
      status: {
        type: "string",
        choices: ["Published", "Draft", "Archived"],
      },
      taxable_weight: {
        type: "float",
        required: true,
      },
      temperature_type: {
        type: "string",
      },
      type: {
        type: "string",
        required: true,
      },
      volume: {
        type: "float",
        required: true,
      },
      weight: {
        type: "float",
        required: true,
      },
    },
  },
  parcels_adr: {
    primaryKey: "id",
    fields: {
      adr_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "adr",
        },
      },
      id: {
        type: "integer",
      },
      parcels_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "parcels",
        },
      },
    },
  },
  pdf_templates: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      is_generic: {
        type: "boolean",
      },
      item_tags: {
        type: "json",
      },
      module_tags: {
        type: "json",
      },
      name: {
        type: "string",
        required: true,
      },
      template: {
        type: "json",
        required: true,
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  profile_alert: {
    primaryKey: "id",
    fields: {
      condition: {
        type: "json",
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      enable: {
        type: "boolean",
      },
      entities_alerts: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities_alerts",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      modified_by_user: {
        type: "boolean",
      },
      profile: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "profiles",
        },
      },
      type: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "type_alerts",
        },
      },
    },
  },
  profiles: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      role_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "roles",
        },
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      user_id: {
        type: "uuid",
        required: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  quotations: {
    primaryKey: "id",
    fields: {
      arrival_terminal: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "terminals",
        },
      },
      booking_number: {
        type: "string",
      },
      booking_type: {
        type: "string",
        required: true,
        choices: ["import", "export"],
      },
      client: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      comments: {
        type: "text",
      },
      commercial: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "customers",
        },
      },
      company: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "oversea_companies",
        },
      },
      consignee: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      containers: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "quotations_containers",
          fk: "quotation",
        },
      },
      custom_company: {
        type: "string",
      },
      customer: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "customers",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      departure_terminal: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "terminals",
        },
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      eta: {
        type: "date",
        required: true,
      },
      etd: {
        type: "date",
        required: true,
      },
      freight_forwarder: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      generated: {
        type: "boolean",
      },
      id: {
        type: "integer",
        readonly: true,
      },
      incoterm: {
        type: "string",
        required: true,
        choices: [
          "EXW",
          "FCA",
          "FAS",
          "FOB",
          "CFR",
          "CIF",
          "CPT",
          "CIP",
          "DAP",
          "DPU",
          "DDP",
        ],
      },
      margin: {
        type: "float",
        required: true,
      },
      number: {
        type: "string",
        required: true,
      },
      orders: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "quotations_orders",
          fk: "quotation",
        },
      },
      parcels: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "quotations_parcels",
          fk: "quotations_id",
          otherFk: "parcels_id",
          to: "parcels",
        },
      },
      parcels_description: {
        type: "text",
      },
      parcels_link_type: {
        type: "string",
        choices: ["folder", "order"],
      },
      parcels_price: {
        type: "float",
      },
      parcels_price_currency: {
        type: "string",
      },
      pdf: {
        type: "uuid",
        relation: {
          kind: "m2o",
          to: "directus_files",
        },
      },
      quotation_status: {
        type: "string",
        required: true,
        choices: [
          "DRAFT",
          "TRANSFERRED_TO_CLIENT",
          "TRANSFERRED_TO_FREIGHT_FORWARDER",
          "ACCEPTED",
          "DECLINED",
          "CANCELED",
        ],
      },
      quotes: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "quotations_quotes",
          fk: "quotation",
        },
      },
      reference: {
        type: "string",
      },
      shipper: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      total_meterage: {
        type: "float",
      },
      total_quantity: {
        type: "integer",
      },
      total_taxable_weight: {
        type: "float",
      },
      total_volume: {
        type: "float",
      },
      total_weight: {
        type: "float",
      },
      transport_type: {
        type: "string",
        required: true,
        choices: ["sea", "air"],
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      validity_end_date: {
        type: "date",
      },
      validity_start_date: {
        type: "date",
      },
    },
  },
  quotations_containers: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      number: {
        type: "string",
        required: true,
      },
      orders: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "quotations_orders",
          fk: "container",
        },
      },
      quotation: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "quotations",
        },
      },
      shipping_method: {
        type: "string",
        choices: ["FCL/FCL", "FCL/LCL", "LCL/LCL", "LCL/FCL", "RORO"],
      },
      type: {
        type: "string",
        required: true,
        choices: [
          "10D",
          "10HC",
          "20D",
          "20HC",
          "20R",
          "40D",
          "40HC",
          "40R",
          "45",
          "20OT",
          "40OT",
          "20FR",
          "40FR",
        ],
      },
    },
  },
  quotations_entities: {
    primaryKey: "id",
    fields: {
      can_edit: {
        type: "boolean",
      },
      entities_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
      },
      quotations_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "quotations",
        },
      },
    },
  },
  quotations_orders: {
    primaryKey: "id",
    fields: {
      consignee: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      container: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "quotations_containers",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      number: {
        type: "string",
        required: true,
      },
      parcels: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "quotations_orders_parcels",
          fk: "quotations_orders_id",
          otherFk: "parcels_id",
          to: "parcels",
        },
      },
      quotation: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "quotations",
        },
      },
      reference: {
        type: "string",
      },
      shipper: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
    },
  },
  quotations_orders_parcels: {
    primaryKey: "id",
    fields: {
      id: {
        type: "integer",
      },
      parcels_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "parcels",
        },
      },
      quotations_orders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "quotations_orders",
        },
      },
    },
  },
  quotations_parcels: {
    primaryKey: "id",
    fields: {
      id: {
        type: "integer",
      },
      parcels_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "parcels",
        },
      },
      quotations_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "quotations",
        },
      },
    },
  },
  quotations_quotes: {
    primaryKey: "id",
    fields: {
      amount_currency: {
        type: "float",
        required: true,
      },
      amount_default_entity_currency: {
        type: "float",
        required: true,
      },
      code: {
        type: "string",
        required: true,
      },
      conversion_rate: {
        type: "float",
        required: true,
      },
      currency: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
      },
      quotation: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "quotations",
        },
      },
      type: {
        type: "string",
        required: true,
        choices: ["purchases", "sales"],
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  quotations_quotes_templates: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
      quotes: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "quotations_quotes_templates_quotes",
          fk: "template",
        },
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
  quotations_quotes_templates_quotes: {
    primaryKey: "id",
    fields: {
      code: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
      },
      template: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "quotations_quotes_templates",
        },
      },
      type: {
        type: "string",
        required: true,
        choices: ["purchases", "sales"],
      },
    },
  },
  roles: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
      permissions: {
        type: "alias",
        required: true,
        relation: {
          kind: "m2m",
          through: "roles_user_permissions",
          fk: "roles_id",
          otherFk: "user_permissions_id",
          to: "user_permissions",
        },
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
    },
  },
  roles_user_permissions: {
    primaryKey: "id",
    fields: {
      id: {
        type: "integer",
      },
      roles_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "roles",
        },
      },
      user_permissions_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "user_permissions",
        },
      },
    },
  },
  sea_bookings: {
    primaryKey: "id",
    fields: {
      agent_code: {
        type: "string",
      },
      arrival_terminal: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "terminals",
        },
      },
      ATA: {
        type: "timestamp",
      },
      ATD: {
        type: "timestamp",
      },
      BL_number: {
        type: "string",
      },
      booking_number: {
        type: "string",
        required: true,
      },
      booking_type: {
        type: "string",
        required: true,
        choices: ["import", "export"],
      },
      co2: {
        type: "float",
      },
      co2_factor: {
        type: "float",
      },
      companies: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "oversea_companies",
        },
      },
      containers: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "containers",
          fk: "sea_booking",
        },
      },
      custom_company: {
        type: "string",
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      departure_terminal: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "terminals",
        },
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      ETA: {
        type: "timestamp",
        required: true,
      },
      ETD: {
        type: "timestamp",
        required: true,
      },
      events: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_bookings_events",
          fk: "sea_bookings_id",
          otherFk: "events_id",
          to: "events",
        },
      },
      folders: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "sea_folders",
          fk: "voyage_id",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      new_ETA: {
        type: "dateTime",
      },
      new_ETD: {
        type: "dateTime",
      },
      ship_name: {
        type: "string",
      },
      shipping_status: {
        type: "string",
        required: true,
        choices: ["CANCELED", "CREATED", "IN_TRANSIT", "ARRIVED_AT_POD"],
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      tracking_id: {
        type: "string",
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      voyage_number: {
        type: "string",
      },
    },
  },
  sea_bookings_events: {
    primaryKey: "id",
    fields: {
      events_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "events",
        },
      },
      id: {
        type: "integer",
      },
      sea_bookings_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_bookings",
        },
      },
    },
  },
  sea_folders: {
    primaryKey: "id",
    fields: {
      billing_reference: {
        type: "string",
      },
      client_reference: {
        type: "string",
      },
      co2: {
        type: "float",
      },
      comments: {
        type: "text",
      },
      consignee: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      container_link_type: {
        type: "string",
        choices: ["full", "dispatched"],
      },
      containers: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_folders_containers",
          fk: "sea_folders_id",
          otherFk: "containers_id",
          to: "containers",
        },
      },
      date: {
        type: "date",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      delivery_date: {
        type: "timestamp",
      },
      entity_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      events: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_folders_events",
          fk: "sea_folders_id",
          otherFk: "events_id",
          to: "events",
        },
      },
      external_references: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "external_references",
          fk: "sea_folder",
        },
      },
      files: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_folders_files",
          fk: "sea_folders_id",
          otherFk: "files_id",
          to: "files",
        },
      },
      folder_number: {
        type: "string",
        required: true,
        readonly: true,
      },
      folder_type: {
        type: "string",
        required: true,
        choices: ["single", "master", "house"],
      },
      folders_entities: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_folders_entities",
          fk: "sea_folders_id",
          otherFk: "entities_id",
          to: "entities",
        },
      },
      houses: {
        type: "alias",
        relation: {
          kind: "o2m",
          to: "sea_folders",
          fk: "master_id",
        },
      },
      id: {
        type: "integer",
        readonly: true,
      },
      incoterm: {
        type: "string",
        required: true,
        choices: [
          "EXW",
          "FCA",
          "FAS",
          "FOB",
          "CFR",
          "CIF",
          "CPT",
          "CIP",
          "DAP",
          "DPU",
          "DDP",
        ],
      },
      main_external_reference: {
        type: "string",
      },
      master_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_folders",
        },
      },
      orders: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_folders_orders",
          fk: "sea_folders_id",
          otherFk: "orders_id",
          to: "orders",
        },
      },
      parcels: {
        type: "alias",
        relation: {
          kind: "m2m",
          through: "sea_folders_parcels",
          fk: "sea_folders_id",
          otherFk: "parcels_id",
          to: "parcels",
        },
      },
      parcels_description: {
        type: "text",
      },
      parcels_link_type: {
        type: "string",
        choices: ["folder", "order"],
      },
      parcels_price: {
        type: "float",
      },
      parcels_price_currency: {
        type: "string",
        choices: ["EUR", "USD"],
      },
      payer_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      pickup_date: {
        type: "timestamp",
      },
      shipper: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "address",
        },
      },
      shipping_status: {
        type: "string",
        required: true,
        choices: [
          "CANCELED",
          "CREATED",
          "PICKED_UP",
          "ARRIVED_AT_POL",
          "IN_TRANSIT",
          "ARRIVED_AT_POD",
          "DELIVERED",
        ],
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
      total_meterage: {
        type: "float",
      },
      total_quantity: {
        type: "integer",
      },
      total_taxable_weight: {
        type: "float",
      },
      total_volume: {
        type: "float",
      },
      total_weight: {
        type: "float",
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      user_updated: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
      voyage_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_bookings",
        },
      },
    },
  },
  sea_folders_containers: {
    primaryKey: "id",
    fields: {
      containers_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "containers",
        },
      },
      id: {
        type: "integer",
      },
      sea_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_folders",
        },
      },
    },
  },
  sea_folders_entities: {
    primaryKey: "id",
    fields: {
      can_edit: {
        type: "boolean",
      },
      entities_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "entities",
        },
      },
      id: {
        type: "integer",
      },
      sea_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_folders",
        },
      },
    },
  },
  sea_folders_events: {
    primaryKey: "id",
    fields: {
      events_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "events",
        },
      },
      id: {
        type: "integer",
      },
      sea_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_folders",
        },
      },
    },
  },
  sea_folders_files: {
    primaryKey: "id",
    fields: {
      files_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "files",
        },
      },
      id: {
        type: "integer",
      },
      sea_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_folders",
        },
      },
    },
  },
  sea_folders_orders: {
    primaryKey: "id",
    fields: {
      id: {
        type: "integer",
      },
      orders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "orders",
        },
      },
      sea_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_folders",
        },
      },
    },
  },
  sea_folders_parcels: {
    primaryKey: "id",
    fields: {
      id: {
        type: "integer",
      },
      parcels_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "parcels",
        },
      },
      sea_folders_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "sea_folders",
        },
      },
    },
  },
  template_roles: {
    primaryKey: "id",
    fields: {
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
      permissions: {
        type: "alias",
        required: true,
        relation: {
          kind: "m2m",
          through: "template_roles_user_permissions",
          fk: "template_roles_id",
          otherFk: "user_permissions_id",
          to: "user_permissions",
        },
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
    },
  },
  template_roles_user_permissions: {
    primaryKey: "id",
    fields: {
      id: {
        type: "integer",
      },
      template_roles_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "template_roles",
        },
      },
      user_permissions_id: {
        type: "integer",
        relation: {
          kind: "m2o",
          to: "user_permissions",
        },
      },
    },
  },
  terminals: {
    primaryKey: "id",
    fields: {
      city: {
        type: "string",
        required: true,
      },
      code: {
        type: "string",
        required: true,
      },
      coordinates: {
        type: "geometry.Point",
      },
      country_id: {
        type: "integer",
        required: true,
        relation: {
          kind: "m2o",
          to: "countries",
        },
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
      type: {
        type: "string",
        required: true,
        choices: ["airport", "port"],
      },
    },
  },
  type_alerts: {
    primaryKey: "id",
    fields: {
      code: {
        type: "string",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      description: {
        type: "json",
        required: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      template_name: {
        type: "string",
        required: true,
      },
    },
  },
  user_permissions: {
    primaryKey: "id",
    fields: {
      actions: {
        type: "json",
        required: true,
        choices: ["create", "read", "update", "delete"],
      },
      collection: {
        type: "string",
        required: true,
      },
      color: {
        type: "string",
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      icon: {
        type: "string",
      },
      id: {
        type: "integer",
        readonly: true,
      },
      name: {
        type: "string",
        required: true,
      },
      status: {
        type: "string",
        choices: ["published", "draft", "archived"],
      },
    },
  },
  user_table_preferences: {
    primaryKey: "id",
    fields: {
      columns: {
        type: "json",
        required: true,
      },
      date_created: {
        type: "timestamp",
        readonly: true,
      },
      date_updated: {
        type: "timestamp",
        readonly: true,
      },
      id: {
        type: "integer",
        readonly: true,
      },
      table_key: {
        type: "string",
        required: true,
      },
      user_created: {
        type: "uuid",
        readonly: true,
        relation: {
          kind: "m2o",
          to: "directus_users",
        },
      },
    },
  },
};
