/**
 * Shape of the committed Pbyp schema snapshot (`directus-schema.ts`),
 * regenerated by `scripts/pbyp-refresh-schema.ts`.
 *
 * Hand-written and imported by the generated module, so the generator's
 * output is type-checked like any other source file rather than trusted.
 */

/**
 * How a relational field is written on the wire.
 *  - `m2o`  : an id (or a nested object, to create the related row inline).
 *  - `o2m`  : an array of child rows, each carrying `fk` back to us.
 *  - `m2m`  : an array of JUNCTION rows — `[{ <otherFk>: <id> }]`, never
 *             `[<id>]`. This is the shape an agent gets wrong most often,
 *             which is why the snapshot carries `through` / `otherFk`
 *             rather than only the far-side collection.
 */
export type PbypRelationShape =
  | { kind: "m2o"; to: string }
  | { kind: "o2m"; to: string; fk: string }
  | { kind: "m2m"; through: string; fk: string; otherFk: string; to: string };

export interface PbypSchemaField {
  /** Directus field type (`string`, `integer`, `date`, `alias`, …). */
  type: string;
  /** Rejected by the API when absent on create. */
  required?: true;
  /** `readonly` in the Directus app — NOT a write prohibition (see below). */
  readonly?: true;
  /** Allowed values, when the field is a dropdown. */
  choices?: string[];
  relation?: PbypRelationShape;
}

export interface PbypSchemaCollection {
  primaryKey: string;
  singleton?: true;
  fields: Record<string, PbypSchemaField>;
}

export type PbypSchema = Record<string, PbypSchemaCollection>;
