import {
  buildSessionKey,
  deleteSessionFile as deleteSessionFileFromS3,
  deleteSessionFolder as deleteSessionFolderFromS3,
  listSessionPaths,
  readSessionFile,
  sanitizeSessionPath,
  uploadSessionFile,
} from "@fretik/shared/lib/chatbot-session-storage";
import { acquireSandbox } from "@fretik/shared/services/e2b/acquire-sandbox";
import {
  execSandboxCommand,
  listSandboxFiles,
  readSandboxFile,
  removeSandboxFile,
  sandboxFileExists,
  writeSandboxFile,
  writeSandboxFiles,
} from "@fretik/shared/services/e2b/files";
import {
  acquireSandboxBootstrapLock,
  bumpAttachmentGeneration,
  getAttachmentGeneration,
  getSandboxIdFromRegistry,
  releaseSandboxBootstrapLock,
} from "@fretik/shared/services/e2b/registry";
import type {
  SandboxArtifact,
  SandboxFileEntry,
  SandboxLease,
} from "@fretik/shared/services/e2b/types";
import { listActiveProviderKeysForConversation } from "@fretik/shared/services/external-apps/connections/list-active-providers-for-conversation";
import { listMcpSnapshotsForConversation } from "@fretik/shared/services/external-apps/mcp/list-snapshots-for-conversation";
import { listEnabledTeamUploadedSkillsWithBodyForConversation } from "@fretik/shared/services/skills/list-enabled-team-uploaded-with-body";
import { randomUUID } from "node:crypto";
import { readdir, stat } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { materializeTeamSkillMd } from "../skills/materialize-team-skill";
import { BUNDLED_SKILLS_DIR, EXTERNAL_APP_SKILLS_DIR } from "../skills/paths";

/**
 * Sandbox-first conversation storage façade.
 *
 * Single source of truth for files visible to the chatbot agent during
 * a conversation. Every file lives directly in the conversation's
 * sandbox at `/workspace/...`. S3 mirrors the durable subset
 * (`attachments/`, `outputs/`) so a sandbox recreated after expiry
 * can be restored.
 *
 * Workspace layout (paths relative to `/workspace`):
 *
 *   attachments/   user uploads in this conversation       (R/W, S3-backed)
 *   outputs/       files generated by python/bash + persisted tool outputs (R/W, S3-backed)
 *     persisted/   tool payloads written out for the agent to re-open:
 *                  large-result envelopes (toolCallId.txt) plus every
 *                  `extract` result (toolCallId.json), written whatever its
 *                  size so python can load the records instead of the model
 *                  retyping them
 *   runs/<runId>/  a workflow run's deliverables, materialised on demand by
 *                  `get_run`                               (R-only, NOT backed up)
 *                  A run executes in its OWN conversation and every file tool
 *                  is scoped to one conversation, so this is how a chat reads
 *                  what a run produced. Durable bytes stay in the run's own S3
 *                  prefix — this is a cache, re-fetched by calling `get_run`
 *                  again. Never mixed with `attachments/`, which is what a
 *                  human attached.
 *   drive/         Drive documents downloaded on demand    (R-only, NOT backed up)
 *   skills/        bundled skills pushed at first init     (R-only)
 *   context/       team/user context snapshots              (R-only)
 *   memories/      the memory tree, mirrored from the DB    (R-only)
 *
 * The Python skill loader (`skill_loader`) is pre-installed at
 * `/opt/fretik/skill_loader.py` by the E2B template build, exposed via
 * a `.pth` file in site-packages. The bundled skill bundles (the
 * SKILL.md + scripts/ + references/ trees) are pushed to
 * `/workspace/skills/` per-conversation by `bootstrapSandbox` below.
 *
 * Concurrency model — multi-replica @fretik/ai:
 *   1. **In-process fast path**: a `Set<sandboxId>` skips bootstrap
 *      when this replica has already done it.
 *   2. **In-process dedup**: parallel calls within a replica share a
 *      single bootstrap promise via `inFlightInits`.
 *   3. **Cross-replica safety**: a Redis lock keyed on `sandboxId`
 *      (`acquireSandboxBootstrapLock`) prevents two replicas from
 *      double-bootstrapping. Losers poll for the `.fretik-init`
 *      marker the winner writes when it's done.
 *   4. **Idempotent operations**: every step is rerun-safe — `mkdir
 *      -p`, file-overwrite write, and skip-on-exists S3 restore.
 *
 * S3 backup model:
 *   - Backups are FIRE-AND-FORGET. A `Map<key, Promise>` chain
 *     serialises uploads for the same `(conv, path)` pair so consecutive
 *     writes land in order on S3 (per-replica).
 *   - Cross-replica races on the same path use last-write-wins
 *     semantics (S3 putObject is atomic). Acceptable in dev; if it
 *     becomes a real problem a Redis lock per `(conv, path)` can be
 *     layered on later.
 */

// ============================================================ //
// LAYOUT CONSTANTS                                              //
// ============================================================ //

export const WORKSPACE_ROOT = "/workspace";

/**
 * Named subdirectories under `/workspace/`. Each top-level entry has a
 * defined contract — see the file header for the read/write rules.
 */
export const WORKSPACE_DIRS = {
  attachments: "attachments",
  outputs: "outputs",
  outputsPersisted: "outputs/persisted",
  runs: "runs",
  drive: "drive",
  skills: "skills",
  context: "context",
  /**
   * PLURAL, matching the `memory` tool's `/memories/` namespace exactly. The
   * two names differed by one letter, for one store, which is a reliable way
   * to make an agent guess a path wrong. Now the rule is one line: the
   * workspace path is the tool path without its leading slash.
   */
  memories: "memories",
} as const;

/**
 * Top-level directories whose content is backed up to S3 so the
 * sandbox can be re-hydrated after expiry. Drive downloads are
 * NOT backed up (cheap to re-download from the documents S3 bucket).
 * Skills/context/memories are read-only from the sandbox's perspective
 * so backup would be redundant.
 */
const BACKUP_ELIGIBLE_DIRS: readonly string[] = ["attachments", "outputs"];

const FRETIK_INIT_MARKER = `${WORKSPACE_ROOT}/.fretik-init`;

/** Polling parameters used when another replica holds the bootstrap lock. */
const BOOTSTRAP_POLL_INTERVAL_MS = 200;
const BOOTSTRAP_POLL_MAX_ITERATIONS = 75; // 15s ceiling.

// ============================================================ //
// IN-PROCESS STATE (per replica)                                //
// ============================================================ //

const initializedSandboxes = new Set<string>();
const inFlightInits = new Map<string, Promise<void>>();
const backupChains = new Map<string, Promise<void>>();

/**
 * Per-sandbox high-water mark of the attachment generation already
 * restored into the workspace. A purely LOCAL optimisation cache over a
 * SHARED source of truth (the Redis generation counter bumped on every
 * attach): a stale entry only ever triggers a redundant, idempotent
 * `restoreFromS3`, never a miss — every replica that serves a code run
 * reads the global counter in `reconcileAttachments` and the workspace
 * is a shared remote object. Safe to keep in-process under horizontal
 * scaling for that reason; do NOT promote correctness decisions onto it.
 */
const restoredAttachmentGen = new Map<string, number>();

const sleep = (ms: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, ms));

// ============================================================ //
// PATH UTILITIES                                                //
// ============================================================ //

const stripLeadingSlash = (path: string): string =>
  path.startsWith("/") ? path.replace(/^\/+/, "") : path;

const stripWorkspacePrefix = (path: string): string => {
  const stripped = stripLeadingSlash(path);
  const prefix = `${stripLeadingSlash(WORKSPACE_ROOT)}/`;
  return stripped.startsWith(prefix) ? stripped.slice(prefix.length) : stripped;
};

const toRelativeWorkspacePath = (path: string): string =>
  sanitizeSessionPath(stripWorkspacePrefix(path));

const isUnderBackupEligibleDir = (relativePath: string): boolean => {
  const head = relativePath.split("/")[0];
  if (head === undefined) return false;
  return BACKUP_ELIGIBLE_DIRS.includes(head);
};

/**
 * Resolve a user-supplied path to a `(relative, absolute)` pair under
 * `/workspace`, or `null` when the input would escape the sandbox via
 * `..` or absolute paths outside `/workspace`. Used by tools that
 * accept agent-supplied paths (`read`, `vision`, `presentFiles`,
 * `download_drive_document`) to enforce the sandbox boundary in a
 * single place.
 *
 * Accepts:
 *   - `attachments/foo.pdf`             → relative form
 *   - `/workspace/attachments/foo.pdf`  → absolute form, stripped
 *   - `foo.pdf`                          → flat basename, returned as-is
 *
 * Anything else (e.g. `/etc/passwd`, `../escape`) returns `null`. The
 * `relative` field is suitable for `readFile`/`writeFile` on the
 * façade; the `absolute` field is what the agent sees in tool output.
 */
export interface ResolvedWorkspacePath {
  /** Path relative to `/workspace`, e.g. `attachments/foo.pdf`. */
  relative: string;
  /** Absolute sandbox path, e.g. `/workspace/attachments/foo.pdf`. */
  absolute: string;
}

export const resolveWorkspacePath = (
  rawPath: string,
): ResolvedWorkspacePath | null => {
  if (rawPath.length === 0) return null;

  // Reject absolute paths that point outside /workspace before any
  // sanitisation strips the prefix.
  if (rawPath.startsWith("/")) {
    const stripped = stripLeadingSlash(rawPath);
    const wsPrefix = `${stripLeadingSlash(WORKSPACE_ROOT)}/`;
    if (
      !stripped.startsWith(wsPrefix) &&
      stripped !== stripLeadingSlash(WORKSPACE_ROOT)
    ) {
      return null;
    }
  }

  // Reject `..` traversal segments. Sanitisation downstream replaces
  // `.` / `..` characters but a literal `../escape` containing forbidden
  // characters would still pass — explicit rejection is clearer.
  for (const segment of rawPath.split("/")) {
    if (segment === "..") return null;
  }

  const relative = toRelativeWorkspacePath(rawPath);
  if (relative.length === 0) return null;

  return {
    relative,
    absolute: `${WORKSPACE_ROOT}/${relative}`,
  };
};

// ============================================================ //
// BUNDLED SKILLS LOADER                                         //
// ============================================================ //

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Path inside the sandbox where the tarball is dropped before
 * extraction. Living under `/tmp` keeps it outside the agent's
 * `/workspace` view (so `list_files` / `read` never surface it) and
 * the sandbox wipes it on restart automatically.
 */
const SKILLS_TARBALL_SANDBOX_PATH = "/tmp/fretik-skills.tar.gz";

/**
 * Build the bundled-skills tarball once at module load and cache the
 * bytes. We use `Bun.Archive` with `{ compress: "gzip" }` — the native
 * code path is faster than spawning `tar` and avoids depending on the
 * host having a particular `tar` flavour.
 *
 * The resulting `.tar.gz` is uploaded once per sandbox bootstrap
 * (single `writeSandboxFile`) and unpacked in-sandbox via `tar -xzf`
 * from `execSandboxCommand`. That replaces what was 188 round-trips
 * (~3.7 MB total) with one transfer (~1-1.5 MB gzipped) + one
 * ~100 ms `tar` invocation — typically 3-5× faster on the critical
 * path of a new conversation's first turn.
 *
 * Cached promise (not bytes) so concurrent calls during boot share
 * the same Bun.Archive build instead of racing.
 */
let cachedSkillsTarball: Promise<Uint8Array | null> | null = null;

const collectSkillFilesForArchive = async (
  diskDir: string,
  archivePrefix: string,
  out: Record<string, Blob>,
): Promise<void> => {
  // Bun.Archive expects POSIX path separators inside the archive.
  // We build them by hand rather than `path.join` so a Windows host
  // producing the build would still yield a portable tarball — and
  // the sandbox is Linux either way.
  const dirents = await readdir(diskDir, { withFileTypes: true }).catch(
    () => null,
  );
  if (!dirents) return;
  for (const entry of dirents) {
    if (entry.name.startsWith(".")) continue;
    const childDisk = `${diskDir}/${entry.name}`;
    const childArchivePath = archivePrefix
      ? `${archivePrefix}/${entry.name}`
      : entry.name;
    if (entry.isDirectory()) {
      await collectSkillFilesForArchive(childDisk, childArchivePath, out);
    } else if (entry.isFile()) {
      // Bun.Archive does NOT await async Blob reads when serializing —
      // passing a raw `Bun.file(...)` reference produces an archive
      // with correct headers but empty file bodies. Read the bytes
      // eagerly here and wrap them in a synchronous Blob so the
      // archive ships actual content. Validated 2026-05-18 — without
      // the eager read the tarball was ~3 KB instead of the expected
      // ~700 KB and every extracted file was 0 bytes.
      const bytes = await Bun.file(childDisk).bytes();
      out[childArchivePath] = new Blob([bytes]);
    }
  }
};

const buildSkillsTarballBytes = async (): Promise<Uint8Array | null> => {
  const startedAt = Date.now();
  const info = await stat(BUNDLED_SKILLS_DIR).catch(() => null);
  if (!info?.isDirectory()) {
    console.warn(
      `[conversation-storage] bundled skills directory missing at ${BUNDLED_SKILLS_DIR}, tarball skipped`,
    );
    return null;
  }

  const files: Record<string, Blob> = {};
  await collectSkillFilesForArchive(BUNDLED_SKILLS_DIR, "", files);

  if (Object.keys(files).length === 0) {
    console.warn(
      "[conversation-storage] no bundled skill files found, tarball skipped",
    );
    return null;
  }

  const archive = new Bun.Archive(files, { compress: "gzip" });
  const bytes = await archive.bytes();
  const duration = Date.now() - startedAt;
  console.log(
    `[conversation-storage] built skills tarball: ${Object.keys(files).length.toString()} files, ${(bytes.byteLength / 1024).toFixed(1)} KB gzipped, ${duration.toString()}ms`,
  );
  return bytes;
};

/**
 * Public accessor — returns the cached tarball bytes (or `null` when
 * the bundled directory is missing / empty). Idempotent and
 * concurrent-safe via the cached promise.
 */
export const getSkillsTarballBytes = (): Promise<Uint8Array | null> => {
  cachedSkillsTarball ??= buildSkillsTarballBytes();
  return cachedSkillsTarball;
};

// ============================================================ //
// BOOTSTRAP                                                     //
// ============================================================ //

/**
 * Public wrapper around the lazy bootstrap. Tools that drive their own
 * sandbox interactions (`python`, `bash`) should call this once before
 * they run code so the workspace layout (`attachments/`, `outputs/`,
 * `skills/`, …) is guaranteed to exist and any S3-backed files are
 * already restored. Idempotent — cheap on subsequent calls (in-process
 * `Set` hit).
 */
export const prepareSandbox = async (
  conversationId: string,
): Promise<SandboxLease> => ensureSandboxReady(conversationId);

/**
 * Pull any attachments uploaded since this replica last restored them
 * into an already-bootstrapped sandbox. Attachments are written to S3
 * only at attach time (no eager E2B push), so a sandbox this replica
 * bootstrapped on an earlier turn won't have files added between turns.
 * The Redis-backed generation counter (bumped on every attach) tells us
 * whether a re-restore is needed — a single Redis GET in the steady
 * state, and `restoreFromS3` is idempotent (skip-on-exists) when it
 * does run.
 */
const reconcileAttachments = async (
  sandboxId: string,
  conversationId: string,
): Promise<void> => {
  const currentGen = await getAttachmentGeneration(conversationId);
  const restoredGen = restoredAttachmentGen.get(sandboxId) ?? 0;
  if (currentGen <= restoredGen) return;
  await restoreFromS3(conversationId);
  restoredAttachmentGen.set(sandboxId, currentGen);
};

/**
 * Idempotent: returns the lease, ensuring the underlying sandbox has
 * been bootstrapped (dirs + skills + S3 restore) for our process AND
 * that any attachment uploaded since the last restore is present.
 */
const ensureSandboxReady = async (
  conversationId: string,
): Promise<SandboxLease> => {
  const lease = await acquireSandbox(conversationId);

  // In-process fast path — still reconcile attachments uploaded since
  // we bootstrapped (cheap Redis GET unless a new file landed).
  if (initializedSandboxes.has(lease.sandboxId)) {
    await reconcileAttachments(lease.sandboxId, conversationId);
    return lease;
  }

  // In-process dedup.
  let pending = inFlightInits.get(lease.sandboxId);
  if (!pending) {
    pending = bootstrapWithLock(lease, conversationId)
      .then(() => {
        initializedSandboxes.add(lease.sandboxId);
      })
      .finally(() => {
        inFlightInits.delete(lease.sandboxId);
      });
    inFlightInits.set(lease.sandboxId, pending);
  }
  await pending;
  // Bootstrap's restoreFromS3 already pulled everything currently in S3;
  // mark this generation covered so the next code run skips the redundant
  // restore until a further attach bumps the counter.
  await reconcileAttachments(lease.sandboxId, conversationId);
  return lease;
};

const bootstrapWithLock = async (
  lease: SandboxLease,
  conversationId: string,
): Promise<void> => {
  // Cheap lock-free check: if another replica already wrote the
  // marker, we can skip the heavy bootstrap and just run S3 restore
  // (idempotent — skips files already present).
  if (await sandboxFileExists(conversationId, FRETIK_INIT_MARKER)) {
    await restoreFromS3(conversationId);
    return;
  }

  const lockToken = randomUUID();
  const gotLock = await acquireSandboxBootstrapLock(lease.sandboxId, lockToken);

  if (!gotLock) {
    // Another replica is bootstrapping. Wait for the marker.
    for (let i = 0; i < BOOTSTRAP_POLL_MAX_ITERATIONS; i++) {
      await sleep(BOOTSTRAP_POLL_INTERVAL_MS);
      if (await sandboxFileExists(conversationId, FRETIK_INIT_MARKER)) {
        await restoreFromS3(conversationId);
        return;
      }
    }
    // Lock holder seemingly wedged or dead — try once more now that
    // the TTL should be expiring.
    const retryToken = randomUUID();
    const retried = await acquireSandboxBootstrapLock(
      lease.sandboxId,
      retryToken,
    );
    if (!retried) {
      throw new Error(
        `Timed out waiting for sandbox bootstrap on ${lease.sandboxId}`,
      );
    }
    try {
      if (await sandboxFileExists(conversationId, FRETIK_INIT_MARKER)) {
        await restoreFromS3(conversationId);
        return;
      }
      await runFullBootstrap(conversationId);
    } finally {
      await releaseSandboxBootstrapLock(lease.sandboxId, retryToken);
    }
    return;
  }

  try {
    // Re-check under the lock — the previous holder may have just
    // finished between our exists check and the lock acquire.
    if (await sandboxFileExists(conversationId, FRETIK_INIT_MARKER)) {
      await restoreFromS3(conversationId);
      return;
    }
    await runFullBootstrap(conversationId);
  } finally {
    await releaseSandboxBootstrapLock(lease.sandboxId, lockToken);
  }
};

const runFullBootstrap = async (conversationId: string): Promise<void> => {
  // Bootstrap is dominated by per-call E2B round-trip latency
  // (~1-2 s baseline for any writeSandboxFile + tar -xzf pair,
  // regardless of payload size). Sequentially that totals 6-8 s on
  // cold start. Every push targets a DISJOINT top-level sub-directory
  // under /workspace, and the staging tarballs land at distinct /tmp
  // paths, so we fan them out with `Promise.all`. Worst case becomes
  // the slowest single push (~2 s) instead of the sum.
  //
  // Safety audit (parallel-safe pre-conditions):
  //  - `createWorkspaceDirs` is awaited BEFORE the fan-out → all
  //    top-level dirs exist before any push runs.
  //  - Top-level destinations are disjoint: bundled skills →
  //    /workspace/skills/{pdf,xlsx,…}, team skills →
  //    /workspace/skills/<team-slug>, external-app skills →
  //    /workspace/skills/<providerKey>, SDK → /workspace/fretik_apps,
  //    S3 restore → /workspace/{attachments,outputs}. Names cannot
  //    collide under current conventions (provider keys are not used
  //    by bundled skills; a team-uploaded skill named after a provider
  //    would already collide in the sequential version, so the risk
  //    isn't introduced by parallelism).
  //  - Each push owns its /tmp tarball filename (different per push,
  //    `rm -f` at the end of its own extract command).
  //  - E2B's daemon serialises filesystem mutations inside the
  //    container; parallel HTTP requests only eliminate the
  //    round-trip dead time, they don't produce concurrent `tar`
  //    processes that fight over the FS.
  //
  // `touchFretikInitMarker` STAYS sequential after the fan-out — its
  // presence is the cross-replica signal that bootstrap finished
  // (see `bootstrapWithLock`).
  await createWorkspaceDirs(conversationId);
  await Promise.all([
    pushBundledSkills(conversationId),
    pushTeamSkills(conversationId),
    pushExternalAppsSdk(conversationId),
    pushExternalAppProviderSkills(conversationId),
    restoreFromS3(conversationId),
  ]);
  // MCP overlay runs AFTER the fan-out, not inside it: it writes stubs into
  // /workspace/fretik_apps/ — the same top-level dir `pushExternalAppsSdk`
  // untars into — so keeping it out of the parallel batch avoids sharing a
  // destination and guarantees the base `_runtime.py`/`__init__.py` are
  // already in place. Soft-fails internally, so it never blocks the marker.
  await pushMcpConnectionOverlay(conversationId);
  await touchFretikInitMarker(conversationId);
};

/**
 * One `mkdir -p` instead of eight `files.makeDir` calls. The directory names
 * are compile-time constants from `WORKSPACE_DIRS`, so there is nothing to
 * quote and nothing a caller can inject. `mkdir -p` is idempotent, which is
 * what the per-call "ignore already-exists" handling was working around.
 */
const createWorkspaceDirs = async (conversationId: string): Promise<void> => {
  const dirs = [
    WORKSPACE_DIRS.attachments,
    WORKSPACE_DIRS.outputs,
    WORKSPACE_DIRS.outputsPersisted,
    WORKSPACE_DIRS.runs,
    WORKSPACE_DIRS.drive,
    WORKSPACE_DIRS.skills,
    WORKSPACE_DIRS.context,
    WORKSPACE_DIRS.memories,
  ].map((dir) => `${WORKSPACE_ROOT}/${dir}`);
  try {
    const result = await execSandboxCommand(
      conversationId,
      `mkdir -p ${dirs.join(" ")}`,
    );
    if (result.exitCode !== 0) {
      console.warn(
        `[conversation-storage] workspace mkdir exited ${result.exitCode.toString()}: ${result.stderr.trim()}`,
      );
    }
  } catch (err) {
    console.warn(
      "[conversation-storage] workspace mkdir failed:",
      err instanceof Error ? err.message : err,
    );
  }
};

/**
 * Push the bundled-skills bundle into `/workspace/skills/` for this
 * conversation. Two-step protocol:
 *
 *   1. Upload the pre-built gzipped tarball to `/tmp/fretik-skills.tar.gz`
 *      (single E2B file write — the bytes are cached in-process so the
 *      filesystem walk + gzip cost is paid once per service boot).
 *   2. `tar -xzf` it into `/workspace/skills/` and `rm` the tarball.
 *
 * Bootstrap is idempotent at the outer layer (`runFullBootstrap` only
 * fires when the `.fretik-init` marker is absent), so this body assumes
 * a clean target. We still pass `--no-overwrite-dir` defensively in
 * case the directory exists with leftover files from a half-completed
 * previous attempt — `tar` falls back to merging in-place which is the
 * idempotent behaviour we want.
 *
 * Soft-fail: a tarball or extract error is logged but not thrown. The
 * agent will then see `_No skills enabled for this team._` on its next
 * turn, which is recoverable on the next conversation bootstrap.
 */
const pushBundledSkills = async (conversationId: string): Promise<void> => {
  const bytes = await getSkillsTarballBytes();
  if (!bytes) {
    console.warn(
      "[conversation-storage] no skills tarball available — skipping skills push",
    );
    return;
  }

  const startedAt = Date.now();
  try {
    await writeSandboxFile(conversationId, SKILLS_TARBALL_SANDBOX_PATH, bytes);
  } catch (err) {
    console.warn(
      "[conversation-storage] failed to upload skills tarball:",
      err instanceof Error ? err.message : err,
    );
    return;
  }

  const skillsDir = `${WORKSPACE_ROOT}/${WORKSPACE_DIRS.skills}`;
  // `set -e` makes the line abort on the first failing step so we surface
  // a meaningful stderr in the catch below instead of a silent skip.
  const extractCommand = [
    "set -e",
    `mkdir -p ${skillsDir}`,
    `tar -xzf ${SKILLS_TARBALL_SANDBOX_PATH} -C ${skillsDir}`,
    `rm -f ${SKILLS_TARBALL_SANDBOX_PATH}`,
  ].join(" && ");

  try {
    const result = await execSandboxCommand(conversationId, extractCommand);
    if (result.exitCode !== 0) {
      console.warn(
        `[conversation-storage] skills tarball extract failed (exit=${result.exitCode.toString()}): ${result.stderr.trim()}`,
      );
      return;
    }
  } catch (err) {
    console.warn(
      "[conversation-storage] skills tarball extract threw:",
      err instanceof Error ? err.message : err,
    );
    return;
  }

  const duration = Date.now() - startedAt;
  console.log(
    `[conversation-storage] pushed skills tarball: ${(bytes.byteLength / 1024).toFixed(1)} KB, ${duration.toString()}ms (upload+extract)`,
  );
};

/**
 * Push every enabled team-uploaded skill into `/workspace/skills/<slug>/SKILL.md`.
 *
 * Bundled skills come in as a single pre-built tarball (see
 * `pushBundledSkills` above) which is fast and idempotent. Team-uploaded
 * skills are low-volume (cap at ~30 per team) and change at human pace,
 * so per-file `writeSandboxFile` calls are simpler than maintaining a
 * second per-team tarball cache — and E2B creates parent directories
 * automatically on `files.write`.
 *
 * Materialised SKILL.md format mirrors the bundled on-disk layout
 * (YAML frontmatter + body) so the chatbot reads both kinds the same
 * way via `bash cat /workspace/skills/<slug>/SKILL.md`.
 *
 * Soft-fail: any error per skill is logged and skipped — the catalogue
 * in the system prompt still lists the skill but `bash cat` will
 * return ENOENT, which the LLM handles gracefully. We avoid hard
 * failures here so a single bad skill doesn't break the whole
 * conversation bootstrap.
 *
 * Resolves teamId from `aiConversations` inside the shared service —
 * keeps `runFullBootstrap`'s signature small (`conversationId`-only)
 * and avoids threading teamId through every call site.
 */
const pushTeamSkills = async (conversationId: string): Promise<void> => {
  let entries: Awaited<
    ReturnType<typeof listEnabledTeamUploadedSkillsWithBodyForConversation>
  >;
  try {
    entries =
      await listEnabledTeamUploadedSkillsWithBodyForConversation(
        conversationId,
      );
  } catch (err) {
    console.warn(
      "[conversation-storage] failed to list team-uploaded skills:",
      err instanceof Error ? err.message : err,
    );
    return;
  }

  if (entries.length === 0) return;

  const startedAt = Date.now();
  const skillsDir = `${WORKSPACE_ROOT}/${WORKSPACE_DIRS.skills}`;
  const encoder = new TextEncoder();

  // `files.write` creates the parent directories it needs, so a batched write
  // is enough — one request for the whole set. The per-file `allSettled` path
  // is kept as the fallback: a batch is all-or-nothing, and one malformed
  // skill should not cost the team every other one.
  const files = entries.map((entry) => ({
    path: `${skillsDir}/${entry.name}/SKILL.md`,
    bytes: encoder.encode(materializeTeamSkillMd(entry)),
  }));

  let written = files.length;
  try {
    await writeSandboxFiles(conversationId, files);
  } catch (err) {
    console.warn(
      "[conversation-storage] team skills batch write failed, retrying one by one:",
      err instanceof Error ? err.message : err,
    );
    const results = await Promise.allSettled(
      files.map((file) =>
        writeSandboxFile(conversationId, file.path, file.bytes),
      ),
    );
    written = results.filter((r) => r.status === "fulfilled").length;
    for (const [i, r] of results.entries()) {
      if (r.status === "rejected") {
        const entry = entries[i];
        console.warn(
          `[conversation-storage] failed to write team skill "${entry?.name ?? "?"}":`,
          r.reason instanceof Error ? r.reason.message : r.reason,
        );
      }
    }
  }

  const duration = Date.now() - startedAt;
  console.log(
    `[conversation-storage] pushed ${written.toString()}/${entries.length.toString()} team skills, ${duration.toString()}ms`,
  );
};

// ============================================================ //
// EXTERNAL APPS — fretik_apps SDK + per-provider skills + auth  //
// ============================================================ //

const EXTERNAL_APPS_SDK_SRC_DIR = resolve(
  __dirname,
  "..",
  "..",
  "sandbox-assets",
  "fretik_apps",
);
const EXTERNAL_APPS_SDK_TARBALL_SANDBOX_PATH =
  "/tmp/fretik-external-apps-sdk.tar.gz";
const EXTERNAL_APPS_SKILL_TARBALL_SANDBOX_PATH = (
  providerKey: string,
): string => `/tmp/fretik-external-apps-skill-${providerKey}.tar.gz`;
const EXTERNAL_APPS_AUTH_FILE = `${WORKSPACE_ROOT}/.fretik/auth.json`;

/**
 * Bundle every `.py` under `sandbox-assets/fretik_apps/` into a gzipped
 * tarball. Mirrors `buildSkillsTarballBytes` for the bundled-skills path:
 *
 *  - Cached at module load (3 files for v1 ~40 KB; bigger as providers ship).
 *  - Single E2B file write + `tar -xzf` per sandbox vs. one round-trip per
 *    file — keeps cold-start latency from scaling with provider count.
 *  - Eager `Bun.file(...).bytes()` because `Bun.Archive` does NOT await
 *    async blob reads at serialization time (validated 2026-05 on the
 *    bundled-skills path — without eager reads the archive headers were
 *    correct but file bodies were 0-byte).
 */
let cachedExternalAppsSdkTarball: Promise<Uint8Array | null> | null = null;

const buildExternalAppsSdkTarballBytes =
  async (): Promise<Uint8Array | null> => {
    const startedAt = Date.now();
    const info = await stat(EXTERNAL_APPS_SDK_SRC_DIR).catch(() => null);
    if (!info?.isDirectory()) {
      console.warn(
        `[conversation-storage] fretik_apps SDK directory missing at ${EXTERNAL_APPS_SDK_SRC_DIR}, tarball skipped`,
      );
      return null;
    }

    const files: Record<string, Blob> = {};
    await collectSkillFilesForArchive(EXTERNAL_APPS_SDK_SRC_DIR, "", files);
    if (Object.keys(files).length === 0) {
      console.warn(
        "[conversation-storage] no fretik_apps SDK files found, tarball skipped",
      );
      return null;
    }

    const archive = new Bun.Archive(files, { compress: "gzip" });
    const bytes = await archive.bytes();
    const duration = Date.now() - startedAt;
    console.log(
      `[conversation-storage] built fretik_apps SDK tarball: ${Object.keys(files).length.toString()} files, ${(bytes.byteLength / 1024).toFixed(1)} KB gzipped, ${duration.toString()}ms`,
    );
    return bytes;
  };

const getExternalAppsSdkTarballBytes = (): Promise<Uint8Array | null> => {
  cachedExternalAppsSdkTarball ??= buildExternalAppsSdkTarballBytes();
  return cachedExternalAppsSdkTarball;
};

/**
 * Per-provider tarballs of `sandbox-assets/skills/<providerKey>/*`,
 * cached lazily. We do NOT bundle every provider into one archive
 * because connected providers differ per team — pushing the Gmail
 * SKILL.md to a team that only has Outlook would waste bandwidth and
 * surface a SKILL the agent has no live connection to drive.
 *
 * Cache is per provider key so the first call for a given provider on
 * a fresh service replica builds the tarball, subsequent calls hit the
 * cached promise.
 */
const cachedExternalAppSkillTarballs = new Map<
  string,
  Promise<Uint8Array | null>
>();

const buildExternalAppSkillTarballBytes = async (
  providerKey: string,
): Promise<Uint8Array | null> => {
  const startedAt = Date.now();
  const srcDir = `${EXTERNAL_APP_SKILLS_DIR}/${providerKey}`;
  const info = await stat(srcDir).catch(() => null);
  if (!info?.isDirectory()) {
    console.warn(
      `[conversation-storage] no skill folder for provider "${providerKey}" at ${srcDir}, tarball skipped`,
    );
    return null;
  }

  const files: Record<string, Blob> = {};
  await collectSkillFilesForArchive(srcDir, "", files);
  if (Object.keys(files).length === 0) {
    console.warn(
      `[conversation-storage] no files in provider "${providerKey}" skill folder, tarball skipped`,
    );
    return null;
  }

  const archive = new Bun.Archive(files, { compress: "gzip" });
  const bytes = await archive.bytes();
  const duration = Date.now() - startedAt;
  console.log(
    `[conversation-storage] built "${providerKey}" skill tarball: ${Object.keys(files).length.toString()} files, ${(bytes.byteLength / 1024).toFixed(1)} KB gzipped, ${duration.toString()}ms`,
  );
  return bytes;
};

const getExternalAppSkillTarballBytes = (
  providerKey: string,
): Promise<Uint8Array | null> => {
  let cached = cachedExternalAppSkillTarballs.get(providerKey);
  if (!cached) {
    cached = buildExternalAppSkillTarballBytes(providerKey);
    cachedExternalAppSkillTarballs.set(providerKey, cached);
  }
  return cached;
};

/**
 * Push the generated Python SDK (`fretik_apps/*.py`) into
 * `/workspace/fretik_apps/`. Pushed unconditionally at bootstrap because
 * the SDK is inert without an `auth.json` (no creds in the sandbox by
 * design — see `lib/external-apps/sandbox-jwt.ts`); having the files
 * present means an early `from fretik_apps import outlook` raises
 * `ModuleNotFoundError` only on an actually missing provider, not on a
 * missing SDK skeleton.
 *
 * Soft-fail: a tarball or extract error is logged but does not throw.
 * The next bootstrap retries.
 */
const pushExternalAppsSdk = async (conversationId: string): Promise<void> => {
  const bytes = await getExternalAppsSdkTarballBytes();
  if (!bytes) return;

  const startedAt = Date.now();
  try {
    await writeSandboxFile(
      conversationId,
      EXTERNAL_APPS_SDK_TARBALL_SANDBOX_PATH,
      bytes,
    );
  } catch (err) {
    console.warn(
      "[conversation-storage] failed to upload fretik_apps SDK tarball:",
      err instanceof Error ? err.message : err,
    );
    return;
  }

  const sdkDir = `${WORKSPACE_ROOT}/fretik_apps`;
  const extractCommand = [
    "set -e",
    `mkdir -p ${sdkDir}`,
    `tar -xzf ${EXTERNAL_APPS_SDK_TARBALL_SANDBOX_PATH} -C ${sdkDir}`,
    `rm -f ${EXTERNAL_APPS_SDK_TARBALL_SANDBOX_PATH}`,
  ].join(" && ");

  try {
    const result = await execSandboxCommand(conversationId, extractCommand);
    if (result.exitCode !== 0) {
      console.warn(
        `[conversation-storage] fretik_apps SDK extract failed (exit=${result.exitCode.toString()}): ${result.stderr.trim()}`,
      );
      return;
    }
  } catch (err) {
    console.warn(
      "[conversation-storage] fretik_apps SDK extract threw:",
      err instanceof Error ? err.message : err,
    );
    return;
  }

  const duration = Date.now() - startedAt;
  console.log(
    `[conversation-storage] pushed fretik_apps SDK tarball: ${(bytes.byteLength / 1024).toFixed(1)} KB, ${duration.toString()}ms (upload+extract)`,
  );
};

/**
 * Push `sandbox-assets/skills/<providerKey>/` into
 * `/workspace/skills/<providerKey>/` for every provider with at least
 * one active connection on this conversation's team.
 *
 * Conditional by design — we don't push the Gmail SKILL.md to a team
 * that only has Outlook. Bundled and uploaded as one tarball per
 * provider so we get one E2B round-trip per active provider instead of
 * one per file: scales with provider count, not provider × files.
 *
 * Called inside `runFullBootstrap` so it fires once per sandbox.
 * If a user adds a connection mid-conversation, the new SKILL.md
 * appears on the next conversation's sandbox — the current sandbox
 * already has the SDK so the agent can still drive existing providers.
 */
const pushExternalAppProviderSkills = async (
  conversationId: string,
): Promise<void> => {
  let providerKeys: string[];
  try {
    providerKeys = await listActiveProviderKeysForConversation(conversationId);
  } catch (err) {
    console.warn(
      "[conversation-storage] failed to list active providers:",
      err instanceof Error ? err.message : err,
    );
    return;
  }

  if (providerKeys.length === 0) return;

  const startedAt = Date.now();
  const skillsDir = `${WORKSPACE_ROOT}/${WORKSPACE_DIRS.skills}`;

  // Parallel-safe: distinct tarball paths + distinct target subdirs.
  await Promise.all(
    providerKeys.map(async (providerKey) => {
      const bytes = await getExternalAppSkillTarballBytes(providerKey);
      if (!bytes) return;

      const tarballPath = EXTERNAL_APPS_SKILL_TARBALL_SANDBOX_PATH(providerKey);
      try {
        await writeSandboxFile(conversationId, tarballPath, bytes);
      } catch (err) {
        console.warn(
          `[conversation-storage] failed to upload "${providerKey}" skill tarball:`,
          err instanceof Error ? err.message : err,
        );
        return;
      }

      const providerDir = `${skillsDir}/${providerKey}`;
      const extractCommand = [
        "set -e",
        `mkdir -p ${providerDir}`,
        `tar -xzf ${tarballPath} -C ${providerDir}`,
        `rm -f ${tarballPath}`,
      ].join(" && ");

      try {
        const result = await execSandboxCommand(conversationId, extractCommand);
        if (result.exitCode !== 0) {
          console.warn(
            `[conversation-storage] "${providerKey}" skill extract failed (exit=${result.exitCode.toString()}): ${result.stderr.trim()}`,
          );
        }
      } catch (err) {
        console.warn(
          `[conversation-storage] "${providerKey}" skill extract threw:`,
          err instanceof Error ? err.message : err,
        );
      }
    }),
  );

  const duration = Date.now() - startedAt;
  console.log(
    `[conversation-storage] pushed external-app skills for [${providerKeys.join(", ")}], ${duration.toString()}ms`,
  );
};

/**
 * Overlay the MCP connections' generated tool surface onto the base SDK.
 *
 * Manifest providers ship their stubs + SKILLs in the committed tarball
 * (`pushExternalAppsSdk` / `pushExternalAppProviderSkills`). MCP connections
 * are introspected at connect time and their compiled surface (Python stub +
 * SKILL index) lives in `external_app_tool_snapshots`, so we materialise it
 * per team here:
 *
 *   - `fretik_apps/<moduleName>.py`  — the generated stub (imports `_runtime`
 *     from the base tarball; a bare submodule, not registered in the base
 *     `__init__.py`, so the agent reaches it via `from fretik_apps import
 *     <moduleName>` as the SKILL instructs).
 *   - `skills/<providerKey>/SKILL.md` — the deterministic tool index.
 *
 * Runs once per sandbox bootstrap. A connection added mid-conversation
 * surfaces on the next conversation's sandbox (identical to the manifest
 * provider-skill contract). Soft-fail throughout: a snapshot fetch or write
 * error is logged and skipped so a single bad connection never wedges the
 * bootstrap.
 */
const pushMcpConnectionOverlay = async (
  conversationId: string,
): Promise<void> => {
  let overlays: Awaited<ReturnType<typeof listMcpSnapshotsForConversation>>;
  try {
    overlays = await listMcpSnapshotsForConversation(conversationId);
  } catch (err) {
    console.warn(
      "[conversation-storage] failed to list MCP snapshots:",
      err instanceof Error ? err.message : err,
    );
    return;
  }

  if (overlays.length === 0) return;

  const startedAt = Date.now();
  const sdkDir = `${WORKSPACE_ROOT}/fretik_apps`;
  const skillsDir = `${WORKSPACE_ROOT}/${WORKSPACE_DIRS.skills}`;
  const encoder = new TextEncoder();

  // One batched write for the 2N files. Falls back to per-file writes so a
  // single bad connection still cannot poison the rest — which is what the
  // `allSettled` loop this replaces was buying, at one round-trip per file.
  const files = overlays.flatMap((overlay) => [
    {
      path: `${sdkDir}/${overlay.moduleName}.py`,
      bytes: encoder.encode(overlay.sdkPy),
    },
    {
      path: `${skillsDir}/${overlay.providerKey}/SKILL.md`,
      bytes: encoder.encode(overlay.skillMd),
    },
  ]);
  try {
    await writeSandboxFiles(conversationId, files);
  } catch (err) {
    console.warn(
      "[conversation-storage] MCP overlay batch write failed, retrying one by one:",
      err instanceof Error ? err.message : err,
    );
    const results = await Promise.allSettled(
      files.map((file) =>
        writeSandboxFile(conversationId, file.path, file.bytes),
      ),
    );
    for (const [i, r] of results.entries()) {
      if (r.status === "rejected") {
        const overlay = overlays[Math.floor(i / 2)];
        console.warn(
          `[conversation-storage] failed to write MCP overlay for "${overlay?.providerKey ?? "?"}":`,
          r.reason instanceof Error ? r.reason.message : r.reason,
        );
      }
    }
  }

  const duration = Date.now() - startedAt;
  console.log(
    `[conversation-storage] pushed MCP overlay for [${overlays.map((o) => o.providerKey).join(", ")}], ${duration.toString()}ms`,
  );
};

/**
 * Write `/workspace/.fretik/auth.json` with the per-turn sandbox JWT,
 * the backend URL the SDK should call back, and the turn id.
 *
 * The Python SDK's `_runtime.py` re-reads this file on every `call()`
 * so a fresh JWT minted by the chatbot handler at turn start propagates
 * to the long-lived Jupyter kernel without restart. Overwrite semantics
 * — never appended; the previous turn's JWT is replaced.
 *
 * Called per-turn from `handlers/chatbot.ts` BEFORE the agent stream
 * starts. Idempotent.
 */
export const writeSandboxAuthFile = async (
  conversationId: string,
  payload: { jwt: string; backendUrl: string; turnId: string },
): Promise<void> => {
  // No `makeSandboxDir` first: `files.write` creates the parent directories
  // it needs ("Writing to a file at path that doesn't exist creates the
  // necessary directories" — E2B SDK). This runs on EVERY turn, including
  // turns that never touch the sandbox otherwise, so the extra round-trip was
  // pure overhead on the request path.
  const body = JSON.stringify({
    jwt: payload.jwt,
    backend_url: payload.backendUrl,
    turn_id: payload.turnId,
  });
  await writeSandboxFile(
    conversationId,
    EXTERNAL_APPS_AUTH_FILE,
    new TextEncoder().encode(body),
  );
};

const touchFretikInitMarker = async (conversationId: string): Promise<void> => {
  try {
    await writeSandboxFile(
      conversationId,
      FRETIK_INIT_MARKER,
      new TextEncoder().encode(new Date().toISOString()),
    );
  } catch (err) {
    console.warn(
      "[conversation-storage] failed to write init marker:",
      err instanceof Error ? err.message : err,
    );
  }
};

/**
 * Pull the conversation's backup-eligible files back into the sandbox.
 *
 * Two phases: decide + fetch in parallel (S3 GETs, independent), then ONE
 * batched sandbox write. The per-file write loop this replaces paid a
 * round-trip per attachment on the cold-start path, where the file count is
 * exactly the user's attachment count. Falls back to per-file writes if the
 * batch is rejected, so one oversized entry cannot cost us the whole restore.
 */
const restoreFromS3 = async (conversationId: string): Promise<void> => {
  const paths = await listSessionPaths(conversationId);
  if (paths.length === 0) return;

  const candidates = await Promise.all(
    paths.map(async (relativePath) => {
      // Backup-eligible only — we never restore bookkeeping dirs.
      if (!isUnderBackupEligibleDir(relativePath)) return null;

      // Idempotent: skip if the sandbox already has the file.
      if (await sandboxFileExists(conversationId, relativePath)) return null;

      const bytes = await readSessionFile(conversationId, relativePath);
      if (!bytes) {
        console.warn(
          `[conversation-storage] restoreFromS3: missing GET for ${conversationId}/${relativePath}`,
        );
        return null;
      }
      return { path: relativePath, bytes };
    }),
  );

  const files = candidates.filter((f) => f !== null);
  if (files.length === 0) return;

  try {
    await writeSandboxFiles(conversationId, files);
  } catch (err) {
    console.warn(
      `[conversation-storage] restoreFromS3: batch write failed (${files.length.toString()} files), retrying one by one:`,
      err instanceof Error ? err.message : err,
    );
    await Promise.all(
      files.map(async (file) => {
        try {
          await writeSandboxFile(conversationId, file.path, file.bytes);
        } catch (writeErr) {
          console.warn(
            `[conversation-storage] restoreFromS3: write failed for ${file.path}:`,
            writeErr instanceof Error ? writeErr.message : writeErr,
          );
        }
      }),
    );
  }
};

// ============================================================ //
// PUBLIC API                                                    //
// ============================================================ //

export interface AttachUserFileResult {
  /** Path relative to `/workspace` (e.g. `attachments/foo.pdf`). */
  path: string;
  /** Absolute sandbox path (`/workspace/attachments/foo.pdf`). */
  absolutePath: string;
}

/**
 * Attach a user-uploaded file to the conversation. Writes the bytes to
 * S3 only — the durable source of truth — and bumps the attachment
 * generation so a warm sandbox re-restores before its next code run.
 *
 * The sandbox is intentionally NOT touched here: `read` and the
 * extraction cache work straight off S3, so the common "attach + ask a
 * question" turn never pays an E2B round-trip. The file is lazily
 * restored into `/workspace/attachments/` by `ensureSandboxReady` the
 * first time `python`/`bash` actually needs the workspace (cold
 * bootstrap → `restoreFromS3`; warm sandbox → `reconcileAttachments`).
 *
 * The S3 upload is awaited synchronously so a downstream consumer that
 * presigns + fetches the object immediately (e.g. Mistral OCR) cannot
 * race the backup and see a 404.
 *
 * The filename is sanitised; the caller (chat-files upload service)
 * is expected to have already deduped against existing names.
 *
 * `contentType` should be the `file.type` from the multipart upload
 * boundary so Scaleway serves the object with the right Content-Type
 * (Mistral OCR otherwise can refuse the fetched blob).
 */
export const attachUserFile = async (
  conversationId: string,
  filename: string,
  bytes: Uint8Array | string,
  contentType?: string,
): Promise<AttachUserFileResult> => {
  const sanitisedFilename = sanitizeSessionPath(filename);
  const relativePath = `${WORKSPACE_DIRS.attachments}/${sanitisedFilename}`;
  const buffer =
    typeof bytes === "string" ? new TextEncoder().encode(bytes) : bytes;
  await uploadSessionFile(conversationId, relativePath, buffer, contentType);
  await bumpAttachmentGeneration(conversationId);
  return {
    path: relativePath,
    absolutePath: `${WORKSPACE_ROOT}/${relativePath}`,
  };
};

interface WriteFileOptions {
  /**
   * Content-Type for the S3 backup. Threaded down to `putObject` so
   * Scaleway serves the object with the proper MIME (otherwise it
   * defaults to `application/octet-stream`). Pass when known —
   * `file.type` from multipart uploads, `text/markdown` for sidecars.
   */
  contentType?: string;
  /**
   * If `true`, awaits the S3 backup before returning. Required when a
   * downstream step will presign + fetch the object immediately
   * (e.g. user attachments → OCR). Defaults to `false` (fire-and-
   * forget) for hot-path writes like sidecars and tool outputs.
   */
  awaitBackup?: boolean;
}

/**
 * Write arbitrary bytes to the sandbox at the given workspace-relative
 * path. Triggers an S3 backup for paths under `attachments/` or
 * `outputs/`. Used internally for OCR sidecars and persisted
 * tool-output envelopes.
 */
export const writeFile = async (
  conversationId: string,
  path: string,
  bytes: Uint8Array | string,
  options: WriteFileOptions = {},
): Promise<void> => {
  await ensureSandboxReady(conversationId);
  const buffer =
    typeof bytes === "string" ? new TextEncoder().encode(bytes) : bytes;
  const relativePath = toRelativeWorkspacePath(path);
  await writeSandboxFile(conversationId, relativePath, buffer);
  if (isUnderBackupEligibleDir(relativePath)) {
    if (options.awaitBackup) {
      await uploadSessionFile(
        conversationId,
        relativePath,
        buffer,
        options.contentType,
      );
    } else {
      queueS3Backup(conversationId, relativePath, buffer, options.contentType);
    }
  }
};

/**
 * Read raw bytes from the sandbox. Throws if the file is missing.
 * Bootstrap (incl. S3 restore) runs lazily on first access so a
 * sandbox recreated after expiry transparently sees its old files.
 */
export const readFile = async (
  conversationId: string,
  path: string,
): Promise<Uint8Array> => {
  await ensureSandboxReady(conversationId);
  const relativePath = toRelativeWorkspacePath(path);
  return readSandboxFile(conversationId, relativePath);
};

/**
 * Read a file as UTF-8 text. Convenience wrapper around `readFile`.
 */
export const readFileText = async (
  conversationId: string,
  path: string,
): Promise<string> => {
  const bytes = await readFile(conversationId, path);
  return new TextDecoder().decode(bytes);
};

/**
 * Check whether a file exists in the sandbox.
 */
export const fileExists = async (
  conversationId: string,
  path: string,
): Promise<boolean> => {
  await ensureSandboxReady(conversationId);
  return sandboxFileExists(conversationId, toRelativeWorkspacePath(path));
};

/**
 * List files in the sandbox. With no `subdir`, lists the entire
 * workspace tree (filtered to regular files). With `subdir`, narrows
 * to that directory.
 */
export const listFiles = async (
  conversationId: string,
  subdir?: string,
): Promise<SandboxFileEntry[]> => {
  await ensureSandboxReady(conversationId);
  return listSandboxFiles(conversationId, subdir);
};

/**
 * Delete a file from S3 (the durable source of truth) and, only if a
 * sandbox currently exists for the conversation, from the workspace too.
 *
 * We deliberately do NOT call `ensureSandboxReady` here: a delete must
 * not trigger a cold E2B bootstrap (skills push + S3 restore) just to
 * remove a file that — under lazy hydration — may never have been
 * restored into the sandbox in the first place. The "does a sandbox
 * exist?" gate is the SHARED Redis registry, not in-process state, so it
 * holds across replicas: whichever replica serves the delete removes the
 * file from the one shared remote sandbox. When no sandbox exists the S3
 * delete alone is sufficient (nothing to re-restore — the object is
 * gone).
 *
 * Best-effort on both sides — a sandbox-side failure still attempts the
 * remote delete.
 */
export const deleteFile = async (
  conversationId: string,
  path: string,
): Promise<void> => {
  const relativePath = toRelativeWorkspacePath(path);
  const sandboxExists = await getSandboxIdFromRegistry(conversationId);
  if (sandboxExists) {
    try {
      await removeSandboxFile(conversationId, relativePath);
    } catch (err) {
      console.warn(
        `[conversation-storage] sandbox delete failed for ${relativePath}:`,
        err instanceof Error ? err.message : err,
      );
    }
  }
  if (isUnderBackupEligibleDir(relativePath)) {
    void deleteSessionFileFromS3(conversationId, relativePath).catch(
      (err: unknown) => {
        console.warn(
          `[conversation-storage] S3 delete failed for ${relativePath}:`,
          err instanceof Error ? err.message : err,
        );
      },
    );
  }
};

/**
 * Mirror sandbox-side changes (created/modified/deleted) to S3. Called
 * after `python` / `bash` runs from `runInSandbox`'s before/after diff.
 *
 * Only paths under backup-eligible top-level dirs (`attachments/`,
 * `outputs/`) are mirrored — agents writing under `drive/` or
 * `skills/` is a no-op (read-only contract by convention).
 */
export const mirrorSandboxChanges = async (
  conversationId: string,
  artifacts: SandboxArtifact[],
  deletedPaths: string[],
): Promise<void> => {
  await Promise.all([
    ...artifacts.map(async (artifact) => {
      if (!isUnderBackupEligibleDir(artifact.path)) return;
      try {
        const bytes = await readSandboxFile(conversationId, artifact.path);
        queueS3Backup(conversationId, artifact.path, bytes);
      } catch (err) {
        console.warn(
          `[conversation-storage] mirror read failed for ${artifact.path}:`,
          err instanceof Error ? err.message : err,
        );
      }
    }),
    ...deletedPaths.map(async (deleted) => {
      if (!isUnderBackupEligibleDir(deleted)) return;
      void deleteSessionFileFromS3(conversationId, deleted).catch(
        (err: unknown) => {
          console.warn(
            `[conversation-storage] S3 delete failed for ${deleted}:`,
            err instanceof Error ? err.message : err,
          );
        },
      );
    }),
  ]);
};

/**
 * Drop every byte for this conversation: the entire S3 session
 * folder. The sandbox itself (if any) is owned by the E2B layer
 * (`releaseSandbox`, `killSandbox`) and naturally expires under
 * autoPause — we don't kill it here.
 *
 * Used by the conversation DELETE handler.
 */
export const deleteConversationStorage = async (
  conversationId: string,
): Promise<void> => {
  await deleteSessionFolderFromS3(conversationId);
};

// ============================================================ //
// S3 BACKUP QUEUE (per-process)                                 //
// ============================================================ //

/**
 * Per-`(conv, path)` in-flight backup chain. Serialises backups so
 * two parallel writes from the same replica land in order on S3.
 *
 * Cross-replica races on the same path use last-write-wins (S3
 * putObject is atomic). If that becomes a real problem a Redis lock
 * keyed on `(conv, path)` can be added later.
 *
 * Fire-and-forget: callers never `await` the chain. Failures are
 * logged inside `uploadSessionFile`.
 */
const queueS3Backup = (
  conversationId: string,
  relativePath: string,
  bytes: Uint8Array,
  contentType?: string,
): void => {
  const key = `${conversationId}::${relativePath}`;
  const previous = backupChains.get(key) ?? Promise.resolve();
  const next = previous
    .catch(() => {
      // Already logged at the failure site; swallow so subsequent
      // backups in the same chain still run.
    })
    .then(async () => {
      await uploadSessionFile(conversationId, relativePath, bytes, contentType);
    });
  backupChains.set(key, next);
  void next.finally(() => {
    if (backupChains.get(key) === next) {
      backupChains.delete(key);
    }
  });
};

// ============================================================ //
// RE-EXPORTS                                                    //
// ============================================================ //

export {
  buildSessionKey,
  sanitizeSessionPath,
  type SandboxArtifact,
  type SandboxFileEntry,
};
