import {
  buildSessionKey,
  deleteSessionFile as deleteSessionFileFromS3,
  deleteSessionFolder as deleteSessionFolderFromS3,
  listSessionPaths,
  readSessionFile,
  sanitizeSessionPath,
  uploadSessionFile,
} from "@fretik/shared/lib/chatbot-session-storage";
import { acquireSandbox } from "@fretik/shared/services/e2b/acquire-sandbox";
import {
  execSandboxCommand,
  listSandboxFiles,
  makeSandboxDir,
  readSandboxFile,
  removeSandboxFile,
  sandboxFileExists,
  writeSandboxFile,
} from "@fretik/shared/services/e2b/files";
import {
  acquireSandboxBootstrapLock,
  releaseSandboxBootstrapLock,
} from "@fretik/shared/services/e2b/registry";
import type {
  SandboxArtifact,
  SandboxFileEntry,
  SandboxLease,
} from "@fretik/shared/services/e2b/types";
import { randomUUID } from "node:crypto";
import { readdir, stat } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Sandbox-first conversation storage façade.
 *
 * Single source of truth for files visible to the chatbot agent during
 * a conversation. Every file lives directly in the conversation's
 * sandbox at `/workspace/...`. S3 mirrors the durable subset
 * (`attachments/`, `outputs/`) so a sandbox recreated after expiry
 * can be restored.
 *
 * Workspace layout (paths relative to `/workspace`):
 *
 *   attachments/   user uploads in this conversation       (R/W, S3-backed)
 *   outputs/       files generated by python/bash + persisted tool outputs (R/W, S3-backed)
 *     persisted/   large tool result envelopes (toolCallId.txt)
 *   drive/         Drive documents downloaded on demand    (R-only, NOT backed up)
 *   skills/        bundled skills pushed at first init     (R-only)
 *   context/       team/user context snapshots              (R-only, future)
 *   memory/        memory tool surface                      (R via tool, future)
 *
 * The Python skill loader (`skill_loader`) is pre-installed at
 * `/opt/fretik/skill_loader.py` by the E2B template build, exposed via
 * a `.pth` file in site-packages. The bundled skill bundles (the
 * SKILL.md + scripts/ + references/ trees) are pushed to
 * `/workspace/skills/` per-conversation by `bootstrapSandbox` below.
 *
 * Concurrency model — multi-replica @fretik/ai:
 *   1. **In-process fast path**: a `Set<sandboxId>` skips bootstrap
 *      when this replica has already done it.
 *   2. **In-process dedup**: parallel calls within a replica share a
 *      single bootstrap promise via `inFlightInits`.
 *   3. **Cross-replica safety**: a Redis lock keyed on `sandboxId`
 *      (`acquireSandboxBootstrapLock`) prevents two replicas from
 *      double-bootstrapping. Losers poll for the `.fretik-init`
 *      marker the winner writes when it's done.
 *   4. **Idempotent operations**: every step is rerun-safe — `mkdir
 *      -p`, file-overwrite write, and skip-on-exists S3 restore.
 *
 * S3 backup model:
 *   - Backups are FIRE-AND-FORGET. A `Map<key, Promise>` chain
 *     serialises uploads for the same `(conv, path)` pair so consecutive
 *     writes land in order on S3 (per-replica).
 *   - Cross-replica races on the same path use last-write-wins
 *     semantics (S3 putObject is atomic). Acceptable in dev; if it
 *     becomes a real problem a Redis lock per `(conv, path)` can be
 *     layered on later.
 */

// ============================================================ //
// LAYOUT CONSTANTS                                              //
// ============================================================ //

export const WORKSPACE_ROOT = "/workspace";

/**
 * Named subdirectories under `/workspace/`. Each top-level entry has a
 * defined contract — see the file header for the read/write rules.
 */
export const WORKSPACE_DIRS = {
  attachments: "attachments",
  outputs: "outputs",
  outputsPersisted: "outputs/persisted",
  drive: "drive",
  skills: "skills",
  context: "context",
  memory: "memory",
} as const;

/**
 * Top-level directories whose content is backed up to S3 so the
 * sandbox can be re-hydrated after expiry. Drive downloads are
 * NOT backed up (cheap to re-download from the documents S3 bucket).
 * Skills/context/memory are read-only from the sandbox's perspective
 * so backup would be redundant.
 */
const BACKUP_ELIGIBLE_DIRS: readonly string[] = ["attachments", "outputs"];

const FRETIK_INIT_MARKER = `${WORKSPACE_ROOT}/.fretik-init`;

/** Polling parameters used when another replica holds the bootstrap lock. */
const BOOTSTRAP_POLL_INTERVAL_MS = 200;
const BOOTSTRAP_POLL_MAX_ITERATIONS = 75; // 15s ceiling.

// ============================================================ //
// IN-PROCESS STATE (per replica)                                //
// ============================================================ //

const initializedSandboxes = new Set<string>();
const inFlightInits = new Map<string, Promise<void>>();
const backupChains = new Map<string, Promise<void>>();

const sleep = (ms: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, ms));

// ============================================================ //
// PATH UTILITIES                                                //
// ============================================================ //

const stripLeadingSlash = (path: string): string =>
  path.startsWith("/") ? path.replace(/^\/+/, "") : path;

const stripWorkspacePrefix = (path: string): string => {
  const stripped = stripLeadingSlash(path);
  const prefix = `${stripLeadingSlash(WORKSPACE_ROOT)}/`;
  return stripped.startsWith(prefix) ? stripped.slice(prefix.length) : stripped;
};

const toRelativeWorkspacePath = (path: string): string =>
  sanitizeSessionPath(stripWorkspacePrefix(path));

const isUnderBackupEligibleDir = (relativePath: string): boolean => {
  const head = relativePath.split("/")[0];
  if (head === undefined) return false;
  return BACKUP_ELIGIBLE_DIRS.includes(head);
};

/**
 * Resolve a user-supplied path to a `(relative, absolute)` pair under
 * `/workspace`, or `null` when the input would escape the sandbox via
 * `..` or absolute paths outside `/workspace`. Used by tools that
 * accept agent-supplied paths (`read`, `vision`, `presentFiles`,
 * `download_drive_document`) to enforce the sandbox boundary in a
 * single place.
 *
 * Accepts:
 *   - `attachments/foo.pdf`             → relative form
 *   - `/workspace/attachments/foo.pdf`  → absolute form, stripped
 *   - `foo.pdf`                          → flat basename, returned as-is
 *
 * Anything else (e.g. `/etc/passwd`, `../escape`) returns `null`. The
 * `relative` field is suitable for `readFile`/`writeFile` on the
 * façade; the `absolute` field is what the agent sees in tool output.
 */
export interface ResolvedWorkspacePath {
  /** Path relative to `/workspace`, e.g. `attachments/foo.pdf`. */
  relative: string;
  /** Absolute sandbox path, e.g. `/workspace/attachments/foo.pdf`. */
  absolute: string;
}

export const resolveWorkspacePath = (
  rawPath: string,
): ResolvedWorkspacePath | null => {
  if (rawPath.length === 0) return null;

  // Reject absolute paths that point outside /workspace before any
  // sanitisation strips the prefix.
  if (rawPath.startsWith("/")) {
    const stripped = stripLeadingSlash(rawPath);
    const wsPrefix = `${stripLeadingSlash(WORKSPACE_ROOT)}/`;
    if (
      !stripped.startsWith(wsPrefix) &&
      stripped !== stripLeadingSlash(WORKSPACE_ROOT)
    ) {
      return null;
    }
  }

  // Reject `..` traversal segments. Sanitisation downstream replaces
  // `.` / `..` characters but a literal `../escape` containing forbidden
  // characters would still pass — explicit rejection is clearer.
  for (const segment of rawPath.split("/")) {
    if (segment === "..") return null;
  }

  const relative = toRelativeWorkspacePath(rawPath);
  if (relative.length === 0) return null;

  return {
    relative,
    absolute: `${WORKSPACE_ROOT}/${relative}`,
  };
};

// ============================================================ //
// BUNDLED SKILLS LOADER                                         //
// ============================================================ //

const __dirname = dirname(fileURLToPath(import.meta.url));
const BUNDLED_SKILLS_SRC_DIR = resolve(__dirname, "..", "skills", "bundled");

/**
 * Path inside the sandbox where the tarball is dropped before
 * extraction. Living under `/tmp` keeps it outside the agent's
 * `/workspace` view (so `list_files` / `read` never surface it) and
 * the sandbox wipes it on restart automatically.
 */
const SKILLS_TARBALL_SANDBOX_PATH = "/tmp/fretik-skills.tar.gz";

/**
 * Build the bundled-skills tarball once at module load and cache the
 * bytes. We use `Bun.Archive` with `{ compress: "gzip" }` — the native
 * code path is faster than spawning `tar` and avoids depending on the
 * host having a particular `tar` flavour.
 *
 * The resulting `.tar.gz` is uploaded once per sandbox bootstrap
 * (single `writeSandboxFile`) and unpacked in-sandbox via `tar -xzf`
 * from `execSandboxCommand`. That replaces what was 188 round-trips
 * (~3.7 MB total) with one transfer (~1-1.5 MB gzipped) + one
 * ~100 ms `tar` invocation — typically 3-5× faster on the critical
 * path of a new conversation's first turn.
 *
 * Cached promise (not bytes) so concurrent calls during boot share
 * the same Bun.Archive build instead of racing.
 */
let cachedSkillsTarball: Promise<Uint8Array | null> | null = null;

const collectSkillFilesForArchive = async (
  diskDir: string,
  archivePrefix: string,
  out: Record<string, Blob>,
): Promise<void> => {
  // Bun.Archive expects POSIX path separators inside the archive.
  // We build them by hand rather than `path.join` so a Windows host
  // producing the build would still yield a portable tarball — and
  // the sandbox is Linux either way.
  const dirents = await readdir(diskDir, { withFileTypes: true }).catch(
    () => null,
  );
  if (!dirents) return;
  for (const entry of dirents) {
    if (entry.name.startsWith(".")) continue;
    const childDisk = `${diskDir}/${entry.name}`;
    const childArchivePath = archivePrefix
      ? `${archivePrefix}/${entry.name}`
      : entry.name;
    if (entry.isDirectory()) {
      await collectSkillFilesForArchive(childDisk, childArchivePath, out);
    } else if (entry.isFile()) {
      // Bun.Archive does NOT await async Blob reads when serializing —
      // passing a raw `Bun.file(...)` reference produces an archive
      // with correct headers but empty file bodies. Read the bytes
      // eagerly here and wrap them in a synchronous Blob so the
      // archive ships actual content. Validated 2026-05-18 — without
      // the eager read the tarball was ~3 KB instead of the expected
      // ~700 KB and every extracted file was 0 bytes.
      const bytes = await Bun.file(childDisk).bytes();
      out[childArchivePath] = new Blob([bytes]);
    }
  }
};

const buildSkillsTarballBytes = async (): Promise<Uint8Array | null> => {
  const startedAt = Date.now();
  const info = await stat(BUNDLED_SKILLS_SRC_DIR).catch(() => null);
  if (!info?.isDirectory()) {
    console.warn(
      `[conversation-storage] bundled skills directory missing at ${BUNDLED_SKILLS_SRC_DIR}, tarball skipped`,
    );
    return null;
  }

  const files: Record<string, Blob> = {};
  await collectSkillFilesForArchive(BUNDLED_SKILLS_SRC_DIR, "", files);

  if (Object.keys(files).length === 0) {
    console.warn(
      "[conversation-storage] no bundled skill files found, tarball skipped",
    );
    return null;
  }

  const archive = new Bun.Archive(files, { compress: "gzip" });
  const bytes = await archive.bytes();
  const duration = Date.now() - startedAt;
  console.log(
    `[conversation-storage] built skills tarball: ${Object.keys(files).length.toString()} files, ${(bytes.byteLength / 1024).toFixed(1)} KB gzipped, ${duration.toString()}ms`,
  );
  return bytes;
};

/**
 * Public accessor — returns the cached tarball bytes (or `null` when
 * the bundled directory is missing / empty). Idempotent and
 * concurrent-safe via the cached promise.
 */
export const getSkillsTarballBytes = (): Promise<Uint8Array | null> => {
  cachedSkillsTarball ??= buildSkillsTarballBytes();
  return cachedSkillsTarball;
};

// ============================================================ //
// BOOTSTRAP                                                     //
// ============================================================ //

/**
 * Public wrapper around the lazy bootstrap. Tools that drive their own
 * sandbox interactions (`python`, `bash`) should call this once before
 * they run code so the workspace layout (`attachments/`, `outputs/`,
 * `skills/`, …) is guaranteed to exist and any S3-backed files are
 * already restored. Idempotent — cheap on subsequent calls (in-process
 * `Set` hit).
 */
export const prepareSandbox = async (
  conversationId: string,
): Promise<SandboxLease> => ensureSandboxReady(conversationId);

/**
 * Idempotent: returns the lease, ensuring the underlying sandbox has
 * been bootstrapped (dirs + skills + S3 restore) for our process.
 */
const ensureSandboxReady = async (
  conversationId: string,
): Promise<SandboxLease> => {
  const lease = await acquireSandbox(conversationId);

  // In-process fast path.
  if (initializedSandboxes.has(lease.sandboxId)) return lease;

  // In-process dedup.
  let pending = inFlightInits.get(lease.sandboxId);
  if (!pending) {
    pending = bootstrapWithLock(lease, conversationId)
      .then(() => {
        initializedSandboxes.add(lease.sandboxId);
      })
      .finally(() => {
        inFlightInits.delete(lease.sandboxId);
      });
    inFlightInits.set(lease.sandboxId, pending);
  }
  await pending;
  return lease;
};

const bootstrapWithLock = async (
  lease: SandboxLease,
  conversationId: string,
): Promise<void> => {
  // Cheap lock-free check: if another replica already wrote the
  // marker, we can skip the heavy bootstrap and just run S3 restore
  // (idempotent — skips files already present).
  if (await sandboxFileExists(conversationId, FRETIK_INIT_MARKER)) {
    await restoreFromS3(conversationId);
    return;
  }

  const lockToken = randomUUID();
  const gotLock = await acquireSandboxBootstrapLock(lease.sandboxId, lockToken);

  if (!gotLock) {
    // Another replica is bootstrapping. Wait for the marker.
    for (let i = 0; i < BOOTSTRAP_POLL_MAX_ITERATIONS; i++) {
      await sleep(BOOTSTRAP_POLL_INTERVAL_MS);
      if (await sandboxFileExists(conversationId, FRETIK_INIT_MARKER)) {
        await restoreFromS3(conversationId);
        return;
      }
    }
    // Lock holder seemingly wedged or dead — try once more now that
    // the TTL should be expiring.
    const retryToken = randomUUID();
    const retried = await acquireSandboxBootstrapLock(
      lease.sandboxId,
      retryToken,
    );
    if (!retried) {
      throw new Error(
        `Timed out waiting for sandbox bootstrap on ${lease.sandboxId}`,
      );
    }
    try {
      if (await sandboxFileExists(conversationId, FRETIK_INIT_MARKER)) {
        await restoreFromS3(conversationId);
        return;
      }
      await runFullBootstrap(conversationId);
    } finally {
      await releaseSandboxBootstrapLock(lease.sandboxId, retryToken);
    }
    return;
  }

  try {
    // Re-check under the lock — the previous holder may have just
    // finished between our exists check and the lock acquire.
    if (await sandboxFileExists(conversationId, FRETIK_INIT_MARKER)) {
      await restoreFromS3(conversationId);
      return;
    }
    await runFullBootstrap(conversationId);
  } finally {
    await releaseSandboxBootstrapLock(lease.sandboxId, lockToken);
  }
};

const runFullBootstrap = async (conversationId: string): Promise<void> => {
  await createWorkspaceDirs(conversationId);
  await pushBundledSkills(conversationId);
  await restoreFromS3(conversationId);
  await touchFretikInitMarker(conversationId);
};

const createWorkspaceDirs = async (conversationId: string): Promise<void> => {
  await Promise.all(
    [
      WORKSPACE_DIRS.attachments,
      WORKSPACE_DIRS.outputs,
      WORKSPACE_DIRS.outputsPersisted,
      WORKSPACE_DIRS.drive,
      WORKSPACE_DIRS.skills,
      WORKSPACE_DIRS.context,
      WORKSPACE_DIRS.memory,
    ].map(async (dir) => {
      try {
        await makeSandboxDir(conversationId, dir);
      } catch (err) {
        console.warn(
          `[conversation-storage] makeDir failed for ${dir}:`,
          err instanceof Error ? err.message : err,
        );
      }
    }),
  );
};

/**
 * Push the bundled-skills bundle into `/workspace/skills/` for this
 * conversation. Two-step protocol:
 *
 *   1. Upload the pre-built gzipped tarball to `/tmp/fretik-skills.tar.gz`
 *      (single E2B file write — the bytes are cached in-process so the
 *      filesystem walk + gzip cost is paid once per service boot).
 *   2. `tar -xzf` it into `/workspace/skills/` and `rm` the tarball.
 *
 * Bootstrap is idempotent at the outer layer (`runFullBootstrap` only
 * fires when the `.fretik-init` marker is absent), so this body assumes
 * a clean target. We still pass `--no-overwrite-dir` defensively in
 * case the directory exists with leftover files from a half-completed
 * previous attempt — `tar` falls back to merging in-place which is the
 * idempotent behaviour we want.
 *
 * Soft-fail: a tarball or extract error is logged but not thrown. The
 * agent will then see `_No skills enabled for this team._` on its next
 * turn, which is recoverable on the next conversation bootstrap.
 */
const pushBundledSkills = async (conversationId: string): Promise<void> => {
  const bytes = await getSkillsTarballBytes();
  if (!bytes) {
    console.warn(
      "[conversation-storage] no skills tarball available — skipping skills push",
    );
    return;
  }

  const startedAt = Date.now();
  try {
    await writeSandboxFile(conversationId, SKILLS_TARBALL_SANDBOX_PATH, bytes);
  } catch (err) {
    console.warn(
      "[conversation-storage] failed to upload skills tarball:",
      err instanceof Error ? err.message : err,
    );
    return;
  }

  const skillsDir = `${WORKSPACE_ROOT}/${WORKSPACE_DIRS.skills}`;
  // `set -e` makes the line abort on the first failing step so we surface
  // a meaningful stderr in the catch below instead of a silent skip.
  const extractCommand = [
    "set -e",
    `mkdir -p ${skillsDir}`,
    `tar -xzf ${SKILLS_TARBALL_SANDBOX_PATH} -C ${skillsDir}`,
    `rm -f ${SKILLS_TARBALL_SANDBOX_PATH}`,
  ].join(" && ");

  try {
    const result = await execSandboxCommand(conversationId, extractCommand);
    if (result.exitCode !== 0) {
      console.warn(
        `[conversation-storage] skills tarball extract failed (exit=${result.exitCode.toString()}): ${result.stderr.trim()}`,
      );
      return;
    }
  } catch (err) {
    console.warn(
      "[conversation-storage] skills tarball extract threw:",
      err instanceof Error ? err.message : err,
    );
    return;
  }

  const duration = Date.now() - startedAt;
  console.log(
    `[conversation-storage] pushed skills tarball: ${(bytes.byteLength / 1024).toFixed(1)} KB, ${duration.toString()}ms (upload+extract)`,
  );
};

const touchFretikInitMarker = async (conversationId: string): Promise<void> => {
  try {
    await writeSandboxFile(
      conversationId,
      FRETIK_INIT_MARKER,
      new TextEncoder().encode(new Date().toISOString()),
    );
  } catch (err) {
    console.warn(
      "[conversation-storage] failed to write init marker:",
      err instanceof Error ? err.message : err,
    );
  }
};

const restoreFromS3 = async (conversationId: string): Promise<void> => {
  const paths = await listSessionPaths(conversationId);
  if (paths.length === 0) return;

  await Promise.all(
    paths.map(async (relativePath) => {
      // Backup-eligible only — we never restore bookkeeping dirs.
      if (!isUnderBackupEligibleDir(relativePath)) return;

      // Idempotent: skip if the sandbox already has the file.
      if (await sandboxFileExists(conversationId, relativePath)) return;

      const bytes = await readSessionFile(conversationId, relativePath);
      if (!bytes) {
        console.warn(
          `[conversation-storage] restoreFromS3: missing GET for ${conversationId}/${relativePath}`,
        );
        return;
      }
      try {
        await writeSandboxFile(conversationId, relativePath, bytes);
      } catch (err) {
        console.warn(
          `[conversation-storage] restoreFromS3: write failed for ${relativePath}:`,
          err instanceof Error ? err.message : err,
        );
      }
    }),
  );
};

// ============================================================ //
// PUBLIC API                                                    //
// ============================================================ //

export interface AttachUserFileResult {
  /** Path relative to `/workspace` (e.g. `attachments/foo.pdf`). */
  path: string;
  /** Absolute sandbox path (`/workspace/attachments/foo.pdf`). */
  absolutePath: string;
}

/**
 * Attach a user-uploaded file to the conversation. Writes it to the
 * sandbox under `attachments/{filename}` and uploads the same bytes
 * to S3 — synchronously, so a downstream consumer (e.g. the OCR
 * preprocessor that hands a presigned URL to Mistral) cannot race the
 * backup and see a 404.
 *
 * The filename is sanitised; the caller (chat-files upload service)
 * is expected to have already deduped against existing names.
 *
 * `contentType` should be the `file.type` from the multipart upload
 * boundary so Scaleway serves the object with the right Content-Type
 * (Mistral OCR otherwise can refuse the fetched blob).
 */
export const attachUserFile = async (
  conversationId: string,
  filename: string,
  bytes: Uint8Array | string,
  contentType?: string,
): Promise<AttachUserFileResult> => {
  const sanitisedFilename = sanitizeSessionPath(filename);
  const relativePath = `${WORKSPACE_DIRS.attachments}/${sanitisedFilename}`;
  await writeFile(conversationId, relativePath, bytes, {
    contentType,
    awaitBackup: true,
  });
  return {
    path: relativePath,
    absolutePath: `${WORKSPACE_ROOT}/${relativePath}`,
  };
};

interface WriteFileOptions {
  /**
   * Content-Type for the S3 backup. Threaded down to `putObject` so
   * Scaleway serves the object with the proper MIME (otherwise it
   * defaults to `application/octet-stream`). Pass when known —
   * `file.type` from multipart uploads, `text/markdown` for sidecars.
   */
  contentType?: string;
  /**
   * If `true`, awaits the S3 backup before returning. Required when a
   * downstream step will presign + fetch the object immediately
   * (e.g. user attachments → OCR). Defaults to `false` (fire-and-
   * forget) for hot-path writes like sidecars and tool outputs.
   */
  awaitBackup?: boolean;
}

/**
 * Write arbitrary bytes to the sandbox at the given workspace-relative
 * path. Triggers an S3 backup for paths under `attachments/` or
 * `outputs/`. Used internally for OCR sidecars and persisted
 * tool-output envelopes.
 */
export const writeFile = async (
  conversationId: string,
  path: string,
  bytes: Uint8Array | string,
  options: WriteFileOptions = {},
): Promise<void> => {
  await ensureSandboxReady(conversationId);
  const buffer =
    typeof bytes === "string" ? new TextEncoder().encode(bytes) : bytes;
  const relativePath = toRelativeWorkspacePath(path);
  await writeSandboxFile(conversationId, relativePath, buffer);
  if (isUnderBackupEligibleDir(relativePath)) {
    if (options.awaitBackup) {
      await uploadSessionFile(
        conversationId,
        relativePath,
        buffer,
        options.contentType,
      );
    } else {
      queueS3Backup(conversationId, relativePath, buffer, options.contentType);
    }
  }
};

/**
 * Read raw bytes from the sandbox. Throws if the file is missing.
 * Bootstrap (incl. S3 restore) runs lazily on first access so a
 * sandbox recreated after expiry transparently sees its old files.
 */
export const readFile = async (
  conversationId: string,
  path: string,
): Promise<Uint8Array> => {
  await ensureSandboxReady(conversationId);
  const relativePath = toRelativeWorkspacePath(path);
  return readSandboxFile(conversationId, relativePath);
};

/**
 * Read a file as UTF-8 text. Convenience wrapper around `readFile`.
 */
export const readFileText = async (
  conversationId: string,
  path: string,
): Promise<string> => {
  const bytes = await readFile(conversationId, path);
  return new TextDecoder().decode(bytes);
};

/**
 * Check whether a file exists in the sandbox.
 */
export const fileExists = async (
  conversationId: string,
  path: string,
): Promise<boolean> => {
  await ensureSandboxReady(conversationId);
  return sandboxFileExists(conversationId, toRelativeWorkspacePath(path));
};

/**
 * List files in the sandbox. With no `subdir`, lists the entire
 * workspace tree (filtered to regular files). With `subdir`, narrows
 * to that directory.
 */
export const listFiles = async (
  conversationId: string,
  subdir?: string,
): Promise<SandboxFileEntry[]> => {
  await ensureSandboxReady(conversationId);
  return listSandboxFiles(conversationId, subdir);
};

/**
 * Delete a file from the sandbox and from S3 if it was backup-eligible.
 * Best-effort on both sides — failure to delete locally still attempts
 * the remote delete.
 */
export const deleteFile = async (
  conversationId: string,
  path: string,
): Promise<void> => {
  await ensureSandboxReady(conversationId);
  const relativePath = toRelativeWorkspacePath(path);
  try {
    await removeSandboxFile(conversationId, relativePath);
  } catch (err) {
    console.warn(
      `[conversation-storage] sandbox delete failed for ${relativePath}:`,
      err instanceof Error ? err.message : err,
    );
  }
  if (isUnderBackupEligibleDir(relativePath)) {
    void deleteSessionFileFromS3(conversationId, relativePath).catch(
      (err: unknown) => {
        console.warn(
          `[conversation-storage] S3 delete failed for ${relativePath}:`,
          err instanceof Error ? err.message : err,
        );
      },
    );
  }
};

/**
 * Mirror sandbox-side changes (created/modified/deleted) to S3. Called
 * after `python` / `bash` runs from `runInSandbox`'s before/after diff.
 *
 * Only paths under backup-eligible top-level dirs (`attachments/`,
 * `outputs/`) are mirrored — agents writing under `drive/` or
 * `skills/` is a no-op (read-only contract by convention).
 */
export const mirrorSandboxChanges = async (
  conversationId: string,
  artifacts: SandboxArtifact[],
  deletedPaths: string[],
): Promise<void> => {
  await Promise.all([
    ...artifacts.map(async (artifact) => {
      if (!isUnderBackupEligibleDir(artifact.path)) return;
      try {
        const bytes = await readSandboxFile(conversationId, artifact.path);
        queueS3Backup(conversationId, artifact.path, bytes);
      } catch (err) {
        console.warn(
          `[conversation-storage] mirror read failed for ${artifact.path}:`,
          err instanceof Error ? err.message : err,
        );
      }
    }),
    ...deletedPaths.map(async (deleted) => {
      if (!isUnderBackupEligibleDir(deleted)) return;
      void deleteSessionFileFromS3(conversationId, deleted).catch(
        (err: unknown) => {
          console.warn(
            `[conversation-storage] S3 delete failed for ${deleted}:`,
            err instanceof Error ? err.message : err,
          );
        },
      );
    }),
  ]);
};

/**
 * Drop every byte for this conversation: the entire S3 session
 * folder. The sandbox itself (if any) is owned by the E2B layer
 * (`releaseSandbox`, `killSandbox`) and naturally expires under
 * autoPause — we don't kill it here.
 *
 * Used by the conversation DELETE handler.
 */
export const deleteConversationStorage = async (
  conversationId: string,
): Promise<void> => {
  await deleteSessionFolderFromS3(conversationId);
};

// ============================================================ //
// S3 BACKUP QUEUE (per-process)                                 //
// ============================================================ //

/**
 * Per-`(conv, path)` in-flight backup chain. Serialises backups so
 * two parallel writes from the same replica land in order on S3.
 *
 * Cross-replica races on the same path use last-write-wins (S3
 * putObject is atomic). If that becomes a real problem a Redis lock
 * keyed on `(conv, path)` can be added later.
 *
 * Fire-and-forget: callers never `await` the chain. Failures are
 * logged inside `uploadSessionFile`.
 */
const queueS3Backup = (
  conversationId: string,
  relativePath: string,
  bytes: Uint8Array,
  contentType?: string,
): void => {
  const key = `${conversationId}::${relativePath}`;
  const previous = backupChains.get(key) ?? Promise.resolve();
  const next = previous
    .catch(() => {
      // Already logged at the failure site; swallow so subsequent
      // backups in the same chain still run.
    })
    .then(async () => {
      await uploadSessionFile(conversationId, relativePath, bytes, contentType);
    });
  backupChains.set(key, next);
  void next.finally(() => {
    if (backupChains.get(key) === next) {
      backupChains.delete(key);
    }
  });
};

// ============================================================ //
// RE-EXPORTS                                                    //
// ============================================================ //

export {
  buildSessionKey,
  sanitizeSessionPath,
  type SandboxArtifact,
  type SandboxFileEntry,
};
