import { z } from "zod";
import db from "../../db";
import type { EpisodeVectorMetadata } from "../../db/schema";
import { callAiService } from "../../lib/ai-service";

const aiVectorizeResponseSchema = z.object({
  success: z.boolean(),
  stats: z
    .object({
      chunksProduced: z.number(),
      chunksEnriched: z.number(),
      rowsInserted: z.number(),
      rowsDropped: z.number(),
    })
    .optional(),
});

/**
 * Re-index one episode from the row itself.
 *
 * Episodes are the only vectorised source with no refresher of their own: they
 * are written inline by the distillers in `@fretik/ai`, so an episode whose
 * vectors go missing afterwards — a crash between the demotion and the delete,
 * a restored dump, a rolled-back parent transaction — had nothing that could
 * rebuild them, and simply left recall. This is what the reconciliation sweep
 * calls to put them back.
 *
 * `ai_episodes` already carries everything the index needs, so no distillation
 * (and no LLM call) is involved: the summary is regenerated by the dreaming
 * pipeline, never here.
 *
 * THROWS by design — the queue owns the retry.
 */
export const refreshEpisodeVectorsOrThrow = async (
  episodeId: string,
): Promise<void> => {
  const episode = await db.query.aiEpisodes.findFirst({
    where: { id: episodeId },
  });
  // Gone, or no longer meant to be found: `hide`/`purge` own that decision and
  // the sweep's orphan pass clears whatever they left behind.
  if (!episode || episode.state !== "active") return;

  const metadata: EpisodeVectorMetadata = {
    kind: episode.kind,
    title: episode.title,
    conversation_id: episode.conversationId,
    anchor_record_id: episode.anchorRecordId,
    occurred_from: episode.occurredFrom?.toISOString() ?? null,
    occurred_to: episode.occurredTo?.toISOString() ?? null,
  };

  const result = await callAiService(
    "/internal/vectorize",
    {
      sourceType: "episodes",
      sourceId: episode.id,
      // The same shape the distillers embed: title, then summary.
      content: `${episode.title}\n\n${episode.summary}`,
      metadata,
      teamId: episode.teamId,
      organizationId: episode.organizationId,
      // A private episode (a single-member conversation) is only its owner's.
      userId: episode.userId,
    },
    aiVectorizeResponseSchema,
    { teamId: episode.teamId, organizationId: episode.organizationId },
  );

  if (!result.success) {
    throw new Error(
      `Vectorize returned success=false for episode ${episodeId}`,
    );
  }
};
