import type { ModelProfile, ModelRole, RoleBinding } from "./types";

/**
 * Seed profiles — the curated brand × tier matrix (every family ships
 * at least one flagship, one workhorse, one utility so the future
 * team picker always has a same-brand option at each tier).
 *
 * `catalog` blocks were read from the OpenRouter models API on
 * 2026-06-11 (`scripts/check-model-catalog.ts` re-verifies them — run
 * it after any provider announcement). Tier placements follow the
 * Artificial Analysis Intelligence Index (June 2026 snapshot):
 * Claude Fable 5 ≈ 65, Opus 4.8 ≈ 61, GPT-5.5 ≈ 60, Gemini 3.5
 * Flash ≈ 55, MiniMax M3 ≈ 55 (leading open weights), DeepSeek V4
 * Pro ≈ 52, GLM-5.1 ≈ 51.
 *
 * `assessment` grades stay `untested` until the C3 promotion gate
 * assigns them; incumbents already serving prod before the gate
 * existed are grandfathered `passed` with no run id. The eval judge
 * (`evals/judge.ts`) intentionally stays OUTSIDE the registry: it must
 * remain a different family from the serving models.
 */

const PDF = "application/pdf";

export const MODEL_PROFILES: Record<string, ModelProfile> = {
  // ───────────────────────── Anthropic ─────────────────────────
  "claude-fable-5": {
    key: "claude-fable-5",
    family: "anthropic",
    tier: "flagship",
    catalog: {
      id: "anthropic/claude-fable-5",
      contextLength: 1_000_000,
      maxCompletionTokens: 128_000,
      pricing: { prompt: 10, completion: 50, inputCacheRead: 1 },
      inputModalities: ["text", "image", "file"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "premium",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: true,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "explicit-breakpoints", maxBreakpoints: 4 },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "claude-opus-4.8": {
    key: "claude-opus-4.8",
    family: "anthropic",
    tier: "flagship",
    catalog: {
      id: "anthropic/claude-opus-4.8",
      contextLength: 1_000_000,
      maxCompletionTokens: 128_000,
      pricing: { prompt: 5, completion: 25, inputCacheRead: 0.5 },
      inputModalities: ["text", "image", "file"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "premium",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: true,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "explicit-breakpoints", maxBreakpoints: 4 },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "claude-sonnet-4.6": {
    key: "claude-sonnet-4.6",
    family: "anthropic",
    tier: "workhorse",
    catalog: {
      id: "anthropic/claude-sonnet-4.6",
      contextLength: 1_000_000,
      maxCompletionTokens: 128_000,
      pricing: { prompt: 3, completion: 15, inputCacheRead: 0.3 },
      inputModalities: ["text", "image", "file"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "premium",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: true,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "explicit-breakpoints", maxBreakpoints: 4 },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "claude-haiku-4.5": {
    key: "claude-haiku-4.5",
    family: "anthropic",
    tier: "utility",
    catalog: {
      id: "anthropic/claude-haiku-4.5",
      contextLength: 200_000,
      maxCompletionTokens: 64_000,
      pricing: { prompt: 1, completion: 5, inputCacheRead: 0.1 },
      inputModalities: ["text", "image", "file"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "standard",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: true,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "explicit-breakpoints", maxBreakpoints: 4 },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },

  // ───────────────────────── OpenAI ─────────────────────────
  "gpt-5.5": {
    key: "gpt-5.5",
    family: "openai",
    tier: "flagship",
    catalog: {
      id: "openai/gpt-5.5",
      contextLength: 1_050_000,
      maxCompletionTokens: 128_000,
      pricing: { prompt: 5, completion: 30, inputCacheRead: 0.5 },
      inputModalities: ["file", "image", "text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "premium",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: true,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "implicit" },
      reasoning: { style: "effort", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "gpt-5.4-mini": {
    key: "gpt-5.4-mini",
    family: "openai",
    tier: "workhorse",
    catalog: {
      id: "openai/gpt-5.4-mini",
      contextLength: 400_000,
      maxCompletionTokens: 128_000,
      pricing: { prompt: 0.75, completion: 4.5, inputCacheRead: 0.075 },
      inputModalities: ["file", "image", "text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "standard",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: true,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "implicit" },
      reasoning: { style: "effort", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "gpt-oss-120b": {
    key: "gpt-oss-120b",
    family: "openai",
    tier: "workhorse",
    catalog: {
      id: "openai/gpt-oss-120b",
      contextLength: 131_072,
      pricing: { prompt: 0.039, completion: 0.18 },
      inputModalities: ["text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "none" },
      reasoning: { style: "effort", defaultLevel: "minimal" },
      provider: { requireParameters: true, zdr: true, sort: "throughput" },
      evalGate: { status: "passed" },
    },
  },
  "gpt-oss-20b": {
    key: "gpt-oss-20b",
    family: "openai",
    tier: "utility",
    catalog: {
      id: "openai/gpt-oss-20b",
      contextLength: 131_072,
      pricing: { prompt: 0.029, completion: 0.14 },
      inputModalities: ["text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "none" },
      reasoning: { style: "effort", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "passed" },
    },
  },
  "gpt-4o-mini": {
    key: "gpt-4o-mini",
    family: "openai",
    tier: "utility",
    catalog: {
      id: "openai/gpt-4o-mini",
      contextLength: 128_000,
      maxCompletionTokens: 16_384,
      pricing: { prompt: 0.15, completion: 0.6, inputCacheRead: 0.075 },
      inputModalities: ["text", "image", "file"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: true,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "implicit" },
      reasoning: { style: "none", defaultLevel: "none" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "passed" },
    },
  },

  // ───────────────────────── Google ─────────────────────────
  "gemini-3.1-pro": {
    key: "gemini-3.1-pro",
    family: "google",
    tier: "flagship",
    catalog: {
      id: "google/gemini-3.1-pro-preview",
      contextLength: 1_048_576,
      maxCompletionTokens: 65_536,
      pricing: { prompt: 2, completion: 12, inputCacheRead: 0.2 },
      inputModalities: ["audio", "file", "image", "text", "video"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "standard",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "implicit" },
      reasoning: { style: "effort", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "gemini-3.5-flash": {
    key: "gemini-3.5-flash",
    family: "google",
    tier: "workhorse",
    catalog: {
      id: "google/gemini-3.5-flash",
      contextLength: 1_048_576,
      maxCompletionTokens: 65_536,
      pricing: { prompt: 1.5, completion: 9, inputCacheRead: 0.15 },
      inputModalities: ["text", "image", "video", "file", "audio"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "standard",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "implicit" },
      reasoning: { style: "effort", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "gemini-3.1-flash-lite": {
    key: "gemini-3.1-flash-lite",
    family: "google",
    tier: "utility",
    catalog: {
      // GA id — the prod vision incumbent ran the `-preview` route of
      // the SAME model until 2026-06; preview routes get sunset, the
      // GA route is the supported one.
      id: "google/gemini-3.1-flash-lite",
      contextLength: 1_048_576,
      maxCompletionTokens: 65_536,
      pricing: { prompt: 0.25, completion: 1.5, inputCacheRead: 0.025 },
      inputModalities: ["text", "image", "video", "file", "audio"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "implicit" },
      reasoning: { style: "effort", defaultLevel: "none" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "passed" },
    },
  },

  // ───────────────────────── Mistral ─────────────────────────
  "mistral-medium-3.5": {
    key: "mistral-medium-3.5",
    family: "mistral",
    tier: "flagship",
    catalog: {
      id: "mistralai/mistral-medium-3-5",
      contextLength: 262_144,
      pricing: { prompt: 1.5, completion: 7.5 },
      inputModalities: ["text", "image", "file"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "standard",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [PDF],
      cache: { strategy: "none" },
      reasoning: { style: "effort", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "mistral-small-2603": {
    key: "mistral-small-2603",
    family: "mistral",
    tier: "workhorse",
    catalog: {
      id: "mistralai/mistral-small-2603",
      contextLength: 262_144,
      pricing: { prompt: 0.15, completion: 0.6, inputCacheRead: 0.015 },
      inputModalities: ["text", "image"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "implicit" },
      reasoning: { style: "effort", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "ministral-8b-2512": {
    key: "ministral-8b-2512",
    family: "mistral",
    tier: "utility",
    catalog: {
      id: "mistralai/ministral-8b-2512",
      contextLength: 262_144,
      pricing: { prompt: 0.15, completion: 0.15, inputCacheRead: 0.015 },
      inputModalities: ["text", "image"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "implicit" },
      reasoning: { style: "none", defaultLevel: "none" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },

  // ───────────────────────── MiniMax ─────────────────────────
  "minimax-m3": {
    key: "minimax-m3",
    family: "minimax",
    tier: "flagship",
    catalog: {
      id: "minimax/minimax-m3",
      contextLength: 1_048_576,
      maxCompletionTokens: 512_000,
      pricing: { prompt: 0.3, completion: 1.2, inputCacheRead: 0.06 },
      // Native image + video input, NO file input — verified 2026-06-11.
      inputModalities: ["text", "image", "video"],
      outputModalities: ["text"],
      // `structured_outputs` absent from the M3 parameter list (unlike M2.7).
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "implicit" },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      // Target flagship default — promotion happens through the C3
      // gate (M3 vs M2.7 baseline), not by hand-flipping this status.
      evalGate: { status: "pending" },
    },
  },
  "minimax-m2.7": {
    key: "minimax-m2.7",
    family: "minimax",
    tier: "workhorse",
    catalog: {
      id: "minimax/minimax-m2.7",
      contextLength: 204_800,
      maxCompletionTokens: 131_072,
      pricing: { prompt: 0.27, completion: 1.08, inputCacheRead: 0.054 },
      inputModalities: ["text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        // 2026-05-07 finding — see types.ts. Do not flip without a
        // fresh provider-pool test.
        parallel: "breaks-provider-pool",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "implicit" },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "passed" },
    },
  },
  "minimax-m2.5": {
    key: "minimax-m2.5",
    family: "minimax",
    tier: "utility",
    catalog: {
      id: "minimax/minimax-m2.5",
      contextLength: 204_800,
      maxCompletionTokens: 196_608,
      pricing: { prompt: 0.15, completion: 0.9, inputCacheRead: 0.05 },
      inputModalities: ["text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "implicit" },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },

  // ───────────────────────── DeepSeek ─────────────────────────
  "deepseek-v4-pro": {
    key: "deepseek-v4-pro",
    family: "deepseek",
    tier: "flagship",
    catalog: {
      id: "deepseek/deepseek-v4-pro",
      contextLength: 1_048_576,
      maxCompletionTokens: 384_000,
      pricing: { prompt: 0.435, completion: 0.87, inputCacheRead: 0.0036 },
      inputModalities: ["text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "implicit" },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "passed" },
    },
  },
  "deepseek-v4-flash": {
    key: "deepseek-v4-flash",
    family: "deepseek",
    tier: "workhorse",
    catalog: {
      id: "deepseek/deepseek-v4-flash",
      contextLength: 1_048_576,
      maxCompletionTokens: 131_072,
      pricing: { prompt: 0.0983, completion: 0.1966, inputCacheRead: 0.0197 },
      inputModalities: ["text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "implicit" },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true, sort: "throughput" },
      evalGate: { status: "passed" },
    },
  },
  "deepseek-v3.2": {
    key: "deepseek-v3.2",
    family: "deepseek",
    tier: "utility",
    catalog: {
      id: "deepseek/deepseek-v3.2",
      contextLength: 131_072,
      maxCompletionTokens: 64_000,
      pricing: { prompt: 0.2288, completion: 0.3432 },
      inputModalities: ["text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      // Routed through Alibaba upstream — needs explicit breakpoints
      // (matches EXPLICIT_CACHE_MODEL_PATTERNS in openrouter-cache.ts).
      cache: { strategy: "explicit-breakpoints", maxBreakpoints: 4 },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },

  // ───────────────────────── GLM (Z.ai) ─────────────────────────
  "glm-5.1": {
    key: "glm-5.1",
    family: "zai",
    tier: "flagship",
    catalog: {
      id: "z-ai/glm-5.1",
      contextLength: 202_752,
      pricing: { prompt: 0.98, completion: 3.08, inputCacheRead: 0.182 },
      inputModalities: ["text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "standard",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "implicit" },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "glm-4.7": {
    key: "glm-4.7",
    family: "zai",
    tier: "workhorse",
    catalog: {
      id: "z-ai/glm-4.7",
      contextLength: 202_752,
      maxCompletionTokens: 131_072,
      pricing: { prompt: 0.4, completion: 1.75, inputCacheRead: 0.08 },
      inputModalities: ["text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "implicit" },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
  "glm-4.7-flash": {
    key: "glm-4.7-flash",
    family: "zai",
    tier: "utility",
    catalog: {
      id: "z-ai/glm-4.7-flash",
      contextLength: 202_752,
      maxCompletionTokens: 16_384,
      pricing: { prompt: 0.06, completion: 0.4, inputCacheRead: 0.01 },
      inputModalities: ["text"],
      outputModalities: ["text"],
      supportedParameters: [
        "tools",
        "tool_choice",
        "max_tokens",
        "reasoning",
        "include_reasoning",
        "response_format",
        "structured_outputs",
      ],
    },
    assessment: {
      costClass: "budget",
      toolCalling: {
        grade: "untested",
        parallel: "untested",
        strictSchemas: false,
      },
      structuredOutput: { grade: "untested" },
      instructionFollowing: "untested",
      nativeFileMimeTypes: [],
      cache: { strategy: "implicit" },
      reasoning: { style: "max-tokens", defaultLevel: "low" },
      provider: { requireParameters: true, zdr: true },
      evalGate: { status: "pending" },
    },
  },
};

/**
 * Default role → profile bindings. Pure code — model env vars are
 * GONE: changing a default is a reviewed PR, per-team / per-
 * conversation overrides arrive with C8 (DB). These defaults
 * reproduce the models prod served before the registry existed; the
 * M3 flagship flip happens through the C3 gate.
 */
export const ROLE_BINDINGS: Record<ModelRole, RoleBinding> = {
  chat: {
    role: "chat",
    profileKey: "minimax-m2.7",
    settingsKind: "chat",
    wrapCache: true,
  },
  "chat-fallback": {
    role: "chat-fallback",
    profileKey: "deepseek-v4-pro",
    settingsKind: "chat",
    wrapCache: true,
  },
  "dispatch-cheap": {
    role: "dispatch-cheap",
    profileKey: "deepseek-v4-flash",
    settingsKind: "chat",
    wrapCache: true,
  },
  "pre-extract": {
    role: "pre-extract",
    profileKey: "deepseek-v4-flash",
    settingsKind: "preextract",
    wrapCache: true,
  },
  "pre-extract-fallback": {
    role: "pre-extract-fallback",
    profileKey: "gpt-oss-120b",
    settingsKind: "preextract",
    wrapCache: true,
  },
  "active-memory": {
    role: "active-memory",
    profileKey: "gpt-oss-20b",
    settingsKind: "active-memory",
    wrapCache: false,
  },
  "compaction-summarizer": {
    role: "compaction-summarizer",
    profileKey: "deepseek-v4-flash",
    settingsKind: "bare",
    wrapCache: false,
  },
  "cheap-tasks": {
    role: "cheap-tasks",
    profileKey: "gpt-oss-20b",
    settingsKind: "bare",
    wrapCache: false,
  },
  vision: {
    role: "vision",
    profileKey: "gemini-3.1-flash-lite",
    settingsKind: "bare",
    wrapCache: false,
  },
  "vision-fallback": {
    role: "vision-fallback",
    profileKey: "gpt-4o-mini",
    settingsKind: "bare",
    wrapCache: false,
  },
};
