import db from "@fretik/shared/db";
import type { RecordAnchor } from "@fretik/shared/services/object-records/anchor";

/**
 * Deterministic graph neighborhood of the records anchored in the user's
 * message (P5). Pure SQL — no LLM, no embeddings: active 1-hop `links`,
 * the anchors' most recent journal events, and the active episodes that
 * anchor on them. Rendered as compact lines the recall judge can lift
 * into the GRAPH section verbatim-ish, with provenance ids.
 *
 * Privacy: episode selection applies the same rule as `listEpisodes` —
 * team episodes (userId NULL) plus the caller's own private ones.
 */

/**
 * Every budget below is PER ANCHOR, and each is enforced by its own query.
 *
 * These used to be GLOBAL caps on one `IN (anchorIds)` query whose rows were
 * then filtered per anchor at render time — so a single hub record holding
 * `MAX_LINKS` recent links consumed the entire fetch and every other anchor
 * rendered ZERO links. Deterministic, silent, and invisible to the eval suite
 * (no case has two anchors, one of them busy). The `domain_event_links` fetch
 * was worse still: capped with no `orderBy` at all, so which rows survived was
 * unspecified — it could return the oldest events and drop today's.
 *
 * One query per anchor is exact rather than probabilistic (widening a shared
 * cap only lowers the odds of starvation), and it costs nothing here: the
 * anchor funnel caps at `MAX_ANCHORS` = 3, the queries are indexed and
 * set-based, they fan out inside the same `Promise.all`, and the whole arm
 * already runs under a 2 500 ms budget.
 */
const MAX_LINKS_PER_ANCHOR = 10;
const MAX_EVENTS_PER_ANCHOR = 5;
/** Global on purpose: the block carries ONE episode budget, not one per anchor. */
const MAX_EPISODES = 3;
/** Episode edges pulled per anchor before the global top-`MAX_EPISODES` rank. */
const EPISODE_EDGE_FETCH_PER_ANCHOR = 30;
/**
 * Recall-usage-weighted recency (MemoryBank-style): base rank is the
 * episode's last update, and each past recall is worth one day of extra
 * freshness — a repeatedly-recalled episode outranks a marginally newer one
 * that never surfaced. Deterministic; no LLM importance scalar (LUFY shows a
 * static importance score underperforms usage signals, and the recall judge
 * already scores relevance dynamically per query).
 */
const RECALL_BOOST_MS = 24 * 60 * 60 * 1000;
/**
 * Ceiling on the usage boost, in recalls (= days). Unbounded it is a feedback
 * loop — recalled → boosted → recalled again — measured 2026-08-05: three
 * 60×-recalled routine episodes ranked now+50d and held all 3 slots against a
 * same-day, directly relevant sibling (stamping also refreshed `updatedAt`
 * until stamp-recall.ts pinned it). Seven days keeps usage decisive between
 * near-peers and irrelevant against a week of content freshness.
 */
const RECALL_BOOST_CAP = 7;

/**
 * Journal kinds the `recent:` line drops: the assistant's own traffic and the
 * record's own birth carry no information a memory block can use.
 *
 * Measured (2026-08): on a supplier follow-up the line rendered as `recent:
 * chat.turn <today>, chat.turn <today>, chat.turn <today>, record.created …,
 * record.created …` — every entry generated by the eval's own turns — and the
 * judge spent a GRAPH bullet copying it INSTEAD of the record's link. The line
 * survives for real activity (`document.uploaded`, `link.created`,
 * `record.updated`, connector/workflow events), which is what it exists for.
 */
const UNINFORMATIVE_EVENT_PREFIXES = [
  "chat.",
  "conversation.",
  "episode.",
  "memory.",
];
const isInformativeEvent = (type: string): boolean =>
  type !== "record.created" &&
  !UNINFORMATIVE_EVENT_PREFIXES.some((p) => type.startsWith(p));

const episodeRankScore = (ep: {
  updatedAt: Date;
  recallCount: number;
}): number =>
  ep.updatedAt.getTime() +
  Math.min(ep.recallCount, RECALL_BOOST_CAP) * RECALL_BOOST_MS;

export interface GraphEpisode {
  id: string;
  title: string;
  summary: string;
  occurredTo: Date | null;
  /**
   * Labels of the matched anchor records this episode is linked to — the
   * deterministic overlap proof. A 25-record episode's summary rarely
   * names every record, so without these labels the judge (correctly,
   * per its overlap rule) discards the episode as unrelated.
   */
  anchorLabels: string[];
}

export interface GraphNeighborhood {
  /** Pre-rendered lines for the judge prompt (empty string = nothing). */
  rendered: string;
  /**
   * Active episodes anchored on the matched records, WITH their summaries —
   * injected as first-class judge candidates so an episode about a record
   * named in the message never depends on the semantic arm's top-K roulette.
   */
  episodes: GraphEpisode[];
}

const day = (d: Date | null): string =>
  d ? d.toISOString().slice(0, 10) : "?";

export const gatherGraphNeighborhood = async (input: {
  anchors: RecordAnchor[];
  userId?: string;
}): Promise<GraphNeighborhood | null> => {
  if (input.anchors.length === 0) return null;
  const anchorIds = input.anchors.map((a) => a.recordId);

  // One query per anchor per relation, all fanned out together — each anchor
  // gets its OWN budget instead of racing the others for a shared one. The
  // returned arrays are positional: index i belongs to `input.anchors[i]`.
  const [linksPerAnchor, subjectEventsPerAnchor, linkedEventsPerAnchor] =
    await Promise.all([
      Promise.all(
        anchorIds.map((anchorId) =>
          db.query.links.findMany({
            where: {
              invalidatedAt: { isNull: true },
              OR: [{ fromRecordId: anchorId }, { toRecordId: anchorId }],
            },
            with: {
              linkType: { columns: { label: true } },
              fromRecord: { columns: { id: true, label: true } },
              toRecord: { columns: { id: true, label: true } },
            },
            orderBy: { createdAt: "desc" },
            limit: MAX_LINKS_PER_ANCHOR,
          }),
        ),
      ),
      Promise.all(
        anchorIds.map((anchorId) =>
          db.query.domainEvents.findMany({
            where: { subjectRecordId: anchorId },
            columns: { id: true, type: true, recordedAt: true },
            orderBy: { id: "desc" },
            // Over-fetch against the informativeness filter below: a record
            // whose recent journal is all `chat.turn` would otherwise render
            // no `recent:` line at all.
            limit: MAX_EVENTS_PER_ANCHOR * 4,
          }),
        ),
      ),
      Promise.all(
        anchorIds.map((anchorId) =>
          db.query.domainEventLinks.findMany({
            where: { recordId: anchorId, status: "confirmed" },
            columns: { recordId: true },
            with: {
              event: { columns: { id: true, type: true, recordedAt: true } },
            },
            // `eventId` is a v7 uuid, so descending IS most-recent-first —
            // the same trick the subject query uses on `domainEvents.id`.
            orderBy: { eventId: "desc" },
            limit: MAX_EVENTS_PER_ANCHOR * 4,
          }),
        ),
      ),
    ]);

  // Episode edges keep a global top-N (the block has one episode budget), but
  // each anchor still contributes its own candidates to that ranking.
  const episodeEdges = (
    await Promise.all(
      anchorIds.map((anchorId) =>
        db.query.aiEpisodeRecords.findMany({
          where: { recordId: anchorId },
          columns: { recordId: true },
          with: { episode: true },
          orderBy: { id: "desc" },
          limit: EPISODE_EDGE_FETCH_PER_ANCHOR,
        }),
      ),
    )
  ).flat();

  // Merge subject + linked events per anchor, most recent first, top 5.
  const eventsByAnchor = new Map<
    string,
    { type: string; recordedAt: Date | null }[]
  >();
  const pushEvent = (
    recordId: string,
    e: { type: string; recordedAt: Date | null },
  ): void => {
    const list = eventsByAnchor.get(recordId) ?? [];
    list.push(e);
    eventsByAnchor.set(recordId, list);
  };
  anchorIds.forEach((anchorId, i) => {
    for (const e of subjectEventsPerAnchor[i] ?? []) {
      if (isInformativeEvent(e.type)) pushEvent(anchorId, e);
    }
    for (const l of linkedEventsPerAnchor[i] ?? []) {
      if (l.event && isInformativeEvent(l.event.type)) {
        pushEvent(anchorId, l.event);
      }
    }
  });
  for (const [recordId, list] of eventsByAnchor) {
    list.sort(
      (a, b) => (b.recordedAt?.getTime() ?? 0) - (a.recordedAt?.getTime() ?? 0),
    );
    eventsByAnchor.set(recordId, list.slice(0, MAX_EVENTS_PER_ANCHOR));
  }

  // Active episodes anchoring on these records — team ones + the caller's own.
  const labelByAnchor = new Map(
    input.anchors.map((a) => [a.recordId, a.label]),
  );
  const episodes = new Map<string, GraphEpisode & { rankScore: number }>();
  for (const edge of episodeEdges) {
    const ep = edge.episode;
    if (!ep || ep.state !== "active") continue;
    if (ep.userId !== null && ep.userId !== input.userId) continue;
    const anchorLabel = labelByAnchor.get(edge.recordId);
    const existing = episodes.get(ep.id);
    if (existing) {
      if (anchorLabel && !existing.anchorLabels.includes(anchorLabel)) {
        existing.anchorLabels.push(anchorLabel);
      }
      continue;
    }
    episodes.set(ep.id, {
      id: ep.id,
      title: ep.title,
      summary: ep.summary,
      occurredTo: ep.occurredTo,
      anchorLabels: anchorLabel ? [anchorLabel] : [],
      rankScore: episodeRankScore(ep),
    });
  }
  const topEpisodes = [...episodes.values()]
    .sort((a, b) => b.rankScore - a.rankScore)
    .slice(0, MAX_EPISODES);

  const lines: string[] = [];
  input.anchors.forEach((anchor, i) => {
    lines.push(`- ${anchor.label} (record:${anchor.recordId})`);
    // Positional: this anchor's own query result, already capped at
    // MAX_LINKS_PER_ANCHOR — no cross-anchor filtering left to do.
    for (const link of linksPerAnchor[i] ?? []) {
      const fromId = link.fromRecord?.id;
      const toId = link.toRecord?.id;
      const from = link.fromRecord?.label ?? "?";
      const to = link.toRecord?.label ?? "?";
      // Surface the NEIGHBOUR's id (the endpoint that isn't the anchor) —
      // the anchor's id is already on its own line and is what the message
      // referred to; the whole value of surfacing an edge is letting the
      // agent drill into the LINKED record, which needs the neighbour's id.
      const neighbourId = fromId === anchor.recordId ? toId : fromId;
      const idTag = neighbourId ? ` (record:${neighbourId})` : "";
      // Bi-temporal edges (temporal link types) carry a validity interval —
      // render it Zep-style so the judge can date the relationship and the
      // agent reasons over "when was this true". NULL validFrom = atemporal
      // link, no interval.
      const interval = link.validFrom
        ? ` (${day(link.validFrom)} → ${link.validTo ? day(link.validTo) : "present"})`
        : "";
      // Qualify AI-inferred edges still in the review band so the judge/agent
      // weighs them as unconfirmed (P8.4). Confirmed edges carry no marker.
      const band = link.status === "suggested" ? " (suggested)" : "";
      lines.push(
        `  · ${from} —${link.linkType?.label ?? "linked"}→ ${to}${idTag}${interval}${band}`,
      );
    }
    const recent = eventsByAnchor.get(anchor.recordId);
    if (recent && recent.length > 0) {
      // Carry the anchor's own marker inline: every renderable graph line is
      // self-contained, so the judge copies a real id, never the section
      // header text ("graph neighborhood") as a stray provenance.
      lines.push(
        `  · recent: ${recent.map((e) => `${e.type} ${day(e.recordedAt)}`).join(", ")} (record:${anchor.recordId})`,
      );
    }
  });
  return {
    rendered: lines.join("\n"),
    episodes: topEpisodes.map(({ rankScore: _rankScore, ...ep }) => ep),
  };
};
