ALTER TABLE "ai_messages" ADD COLUMN "seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_messages_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "ai_messages" ADD COLUMN "turn_id" uuid;--> statement-breakpoint
-- Postgres backfills a new identity column in PHYSICAL row order, which is
-- not chronological. Renumber existing rows by (created_at, id): created_at
-- ties only happen within a turn's multi-row INSERT, where the uuid-v7 ids
-- are monotonic — so this ordering is the true generation order. `seq` is
-- BY DEFAULT (not ALWAYS) identity precisely so this UPDATE is allowed.
WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn
  FROM "ai_messages"
)
UPDATE "ai_messages" m
SET seq = o.rn
FROM ordered o
WHERE m.id = o.id;--> statement-breakpoint
-- Move the sequence past the backfilled range so future inserts don't collide.
SELECT setval(pg_get_serial_sequence('ai_messages', 'seq'), (SELECT COALESCE(MAX(seq), 1) FROM "ai_messages"));--> statement-breakpoint
CREATE INDEX "ai_messages_conversation_seq_idx" ON "ai_messages" ("conversation_id","seq");