import type { FileSurface, FileTypeDef } from "./types";

// ============================================================================ //
// FILE-TYPE REGISTRY — DATA                                                    //
// ----------------------------------------------------------------------------//
// The ONE place a file type is declared. Every MIME list, extension list,      //
// accept attribute, icon, colour and routing decision in the monorepo is       //
// derived from this array (see `derive.ts`) — nothing re-declares them.        //
//                                                                             //
// Adding a type = adding one entry here. Adding a FIELD to an entry means      //
// teaching every surface at once, which is the point.                          //
// ============================================================================ //

/** Everything a document-like file is accepted by. Videos are the exception. */
const DOC_SURFACES: readonly FileSurface[] = [
  "drive",
  "chatbot",
  "context",
  "workflow-form",
];

/** Raster photos double as avatar / logo sources. */
const PHOTO_SURFACES: readonly FileSurface[] = [...DOC_SURFACES, "avatar"];

/** Videos carry no text: chat / workflow input only, never the Drive. */
const VIDEO_SURFACES: readonly FileSurface[] = ["chatbot", "workflow-form"];

export const FILE_TYPES: readonly FileTypeDef[] = [
  // ------------------------------------------------------------------ //
  // Documents — Mistral OCR reads them natively (embedded-image text).  //
  // ------------------------------------------------------------------ //
  {
    id: "pdf",
    mime: "application/pdf",
    aliasMimes: ["application/x-pdf"],
    extensions: [".pdf"],
    family: "document",
    textual: false,
    icon: "i-ph-file-pdf",
    color: "red",
    extraction: "mistral-ocr",
    thumbnail: "pdf-first-page",
    viewer: "pdf",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "docx",
    mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    aliasMimes: [],
    extensions: [".docx"],
    family: "document",
    textual: false,
    icon: "i-ph-file-doc",
    color: "blue",
    extraction: "mistral-ocr",
    thumbnail: "libreoffice",
    viewer: "docx",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "doc",
    mime: "application/msword",
    aliasMimes: [],
    extensions: [".doc"],
    family: "document",
    textual: false,
    icon: "i-ph-file-doc",
    color: "blue",
    extraction: "mistral-ocr",
    thumbnail: "libreoffice",
    // No browser reads the binary Compound File format — `@vue-office/docx`
    // parses `word/document.xml` out of an OOXML zip and nothing else. The
    // same LibreOffice that already makes the thumbnail makes the preview.
    viewer: "pdf-converted",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "docm",
    mime: "application/vnd.ms-word.document.macroenabled.12",
    aliasMimes: [],
    extensions: [".docm"],
    family: "document",
    textual: false,
    icon: "i-ph-file-doc",
    color: "blue",
    // A macro-enabled document is an OOXML zip with a `vbaProject.bin`
    // beside the parts `.docx` carries. Mistral publishes no word on the
    // format, so it takes the LibreOffice route rather than betting a
    // silent extraction failure on the resemblance.
    extraction: "convert-ocr",
    thumbnail: "libreoffice",
    viewer: "pdf-converted",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "odt",
    mime: "application/vnd.oasis.opendocument.text",
    aliasMimes: [],
    extensions: [".odt"],
    family: "document",
    textual: false,
    icon: "i-ph-file-doc",
    color: "blue",
    // Mistral OCR has no native OpenDocument reader — convert to PDF first.
    extraction: "convert-ocr",
    thumbnail: "libreoffice",
    viewer: "pdf-converted",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "rtf",
    mime: "application/rtf",
    aliasMimes: ["text/rtf"],
    extensions: [".rtf"],
    family: "document",
    textual: false,
    icon: "i-ph-file-doc",
    color: "blue",
    extraction: "convert-ocr",
    thumbnail: "libreoffice",
    viewer: "pdf-converted",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },

  // ------------------------------------------------------------------ //
  // Spreadsheets — exceljs markdown tables; the agent prefers python.   //
  // ------------------------------------------------------------------ //
  {
    id: "xlsx",
    mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    aliasMimes: [],
    extensions: [".xlsx"],
    family: "spreadsheet",
    textual: false,
    icon: "i-ph-file-xls",
    color: "green",
    extraction: "spreadsheet",
    thumbnail: "libreoffice",
    viewer: "xlsx",
    agentAccess: "tabular",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "xls",
    mime: "application/vnd.ms-excel",
    aliasMimes: [],
    extensions: [".xls"],
    family: "spreadsheet",
    textual: false,
    icon: "i-ph-file-xls",
    color: "green",
    extraction: "spreadsheet",
    thumbnail: "libreoffice",
    // `@vue-office/excel` bundles SheetJS, whose BIFF2-BIFF8 reader opens
    // the legacy binary workbook — the same branch that serves `.xlsx`.
    viewer: "xlsx",
    agentAccess: "tabular",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "xlsm",
    mime: "application/vnd.ms-excel.sheet.macroenabled.12",
    aliasMimes: [],
    extensions: [".xlsm"],
    family: "spreadsheet",
    textual: false,
    icon: "i-ph-file-xls",
    color: "green",
    // Unlike its Word and PowerPoint siblings this one needs no detour:
    // exceljs opens a macro-enabled workbook as the OOXML zip it is, and
    // so does SheetJS in the browser.
    extraction: "spreadsheet",
    thumbnail: "libreoffice",
    viewer: "xlsx",
    agentAccess: "tabular",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "ods",
    mime: "application/vnd.oasis.opendocument.spreadsheet",
    aliasMimes: [],
    extensions: [".ods"],
    family: "spreadsheet",
    textual: false,
    icon: "i-ph-file-xls",
    color: "green",
    // exceljs cannot open ODS; PDF conversion keeps the values readable.
    extraction: "convert-ocr",
    thumbnail: "libreoffice",
    // Extraction and preview disagree on purpose: SheetJS reads ODS in the
    // browser (`parse_ods`) even though exceljs, which does the extracting,
    // does not. The reader that can do the job does it.
    viewer: "xlsx",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "csv",
    mime: "text/csv",
    aliasMimes: ["application/csv", "text/tab-separated-values"],
    extensions: [".csv", ".tsv"],
    family: "spreadsheet",
    textual: true,
    icon: "i-ph-file-csv",
    color: "green",
    extraction: "spreadsheet",
    thumbnail: "libreoffice",
    viewer: "csv",
    // Unlike XLSX, a CSV is already UTF-8 — the agent reads it verbatim.
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },

  // ------------------------------------------------------------------ //
  // Presentations                                                       //
  // ------------------------------------------------------------------ //
  {
    id: "pptx",
    mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    aliasMimes: [],
    extensions: [".pptx"],
    family: "presentation",
    textual: false,
    icon: "i-ph-file-ppt",
    color: "orange",
    extraction: "mistral-ocr",
    thumbnail: "libreoffice",
    viewer: "pptx",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "ppt",
    mime: "application/vnd.ms-powerpoint",
    aliasMimes: [],
    extensions: [".ppt"],
    family: "presentation",
    textual: false,
    icon: "i-ph-file-ppt",
    color: "orange",
    extraction: "mistral-ocr",
    thumbnail: "libreoffice",
    viewer: "pdf-converted",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "pptm",
    mime: "application/vnd.ms-powerpoint.presentation.macroenabled.12",
    aliasMimes: [],
    extensions: [".pptm"],
    family: "presentation",
    textual: false,
    icon: "i-ph-file-ppt",
    color: "orange",
    // Same reasoning as `docm`: OOXML underneath, undocumented upstream.
    extraction: "convert-ocr",
    thumbnail: "libreoffice",
    viewer: "pdf-converted",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "odp",
    mime: "application/vnd.oasis.opendocument.presentation",
    aliasMimes: [],
    extensions: [".odp"],
    family: "presentation",
    textual: false,
    icon: "i-ph-file-ppt",
    color: "orange",
    extraction: "convert-ocr",
    thumbnail: "libreoffice",
    viewer: "pdf-converted",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },

  // ------------------------------------------------------------------ //
  // Prose text                                                          //
  // ------------------------------------------------------------------ //
  {
    id: "txt",
    // Owner of `text/plain`: the `code` and `config` defs share this MIME
    // but are reachable by extension only.
    mime: "text/plain",
    aliasMimes: [],
    extensions: [".txt", ".log"],
    family: "text",
    textual: true,
    icon: "i-ph-file-txt",
    color: "neutral",
    extraction: "text",
    thumbnail: "none",
    viewer: "text",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
  },
  {
    id: "markdown",
    mime: "text/markdown",
    aliasMimes: ["text/x-markdown"],
    // `.mdx` is markdown with JSX in it — no registered MIME of its own,
    // and nothing downstream needs to tell the two apart.
    extensions: [".md", ".markdown", ".mdx"],
    family: "markdown",
    textual: true,
    icon: "i-ph-file-md",
    color: "neutral",
    extraction: "text",
    // Gotenberg renders markdown through Chromium — the only way to give
    // the format Fretik authors a real thumbnail (LibreOffice can't import it).
    thumbnail: "chromium-screenshot",
    viewer: "markdown",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
  },

  {
    id: "markup",
    // Lightweight markup languages, none of which registered a MIME. They
    // share `text/plain` with `txt` and are reached by extension, exactly
    // as `code` and `config` are.
    mime: "text/plain",
    aliasMimes: [],
    extensions: [".rst", ".adoc", ".asciidoc", ".tex"],
    // `markdown`, not `code`: what a reader uploads here is prose with
    // markup in it, and the family is what names the format in the copy
    // under a dropzone.
    family: "markdown",
    textual: true,
    icon: "i-ph-file-text",
    color: "neutral",
    extraction: "text",
    // Gotenberg's markdown route speaks CommonMark and would render
    // reStructuredText directives as literal text.
    thumbnail: "none",
    viewer: "code",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
    extensionOnly: true,
  },
  {
    id: "subtitles",
    mime: "text/vtt",
    aliasMimes: ["application/x-subrip"],
    extensions: [".vtt", ".srt"],
    family: "text",
    textual: true,
    icon: "i-ph-closed-captioning",
    color: "neutral",
    extraction: "text",
    thumbnail: "none",
    viewer: "text",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
  },

  // ------------------------------------------------------------------ //
  // Web                                                                 //
  // ------------------------------------------------------------------ //
  {
    id: "html",
    mime: "text/html",
    aliasMimes: ["application/xhtml+xml"],
    extensions: [".html", ".htm", ".xhtml"],
    family: "html",
    textual: true,
    icon: "i-ph-file-html",
    color: "cyan",
    // Markdown sidecar for search / manifests; `read` still returns the
    // raw source so the agent can inspect or rewrite the markup itself.
    extraction: "html",
    thumbnail: "chromium-screenshot",
    viewer: "html-iframe",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },

  // ------------------------------------------------------------------ //
  // Source code — one def, refined per-extension for the language.      //
  // ------------------------------------------------------------------ //
  {
    id: "code",
    mime: "text/plain",
    aliasMimes: [],
    extensions: [
      ".js",
      ".jsx",
      ".mjs",
      ".cjs",
      ".ts",
      ".tsx",
      ".mts",
      ".cts",
      ".vue",
      ".svelte",
      ".py",
      ".pyi",
      ".rb",
      ".go",
      ".rs",
      ".c",
      ".h",
      ".cpp",
      ".cc",
      ".cxx",
      ".hpp",
      ".cs",
      ".java",
      ".kt",
      ".kts",
      ".swift",
      ".php",
      ".sh",
      ".bash",
      ".zsh",
      ".fish",
      ".ps1",
      ".sql",
      ".r",
      ".lua",
      ".pl",
      ".scala",
      ".dart",
      ".ex",
      ".exs",
      ".erl",
      ".hs",
      ".clj",
      ".css",
      ".scss",
      ".less",
      ".graphql",
      ".gql",
      ".proto",
      ".tf",
      ".tfvars",
      ".dockerfile",
      ".ipynb",
      ".diff",
      ".patch",
    ],
    family: "code",
    textual: true,
    icon: "i-ph-file-code",
    color: "amber",
    extraction: "text",
    thumbnail: "none",
    viewer: "code",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
    extensionOnly: true,
  },

  // ------------------------------------------------------------------ //
  // Structured data / configuration                                     //
  // ------------------------------------------------------------------ //
  {
    id: "json",
    mime: "application/json",
    aliasMimes: ["application/ld+json", "text/json"],
    extensions: [".json", ".jsonc", ".json5", ".jsonl", ".geojson"],
    family: "data",
    textual: true,
    icon: "i-ph-brackets-curly",
    color: "amber",
    extraction: "text",
    thumbnail: "none",
    viewer: "code",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
  },
  {
    id: "yaml",
    mime: "application/yaml",
    aliasMimes: ["application/x-yaml", "text/yaml", "text/x-yaml"],
    extensions: [".yaml", ".yml"],
    family: "data",
    textual: true,
    icon: "i-ph-file-code",
    color: "amber",
    extraction: "text",
    thumbnail: "none",
    viewer: "code",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
  },
  {
    id: "xml",
    mime: "application/xml",
    aliasMimes: ["text/xml"],
    extensions: [".xml", ".xsd", ".xsl", ".plist"],
    family: "data",
    textual: true,
    icon: "i-ph-file-code",
    color: "amber",
    extraction: "text",
    thumbnail: "none",
    viewer: "code",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
  },
  {
    id: "toml",
    mime: "application/toml",
    aliasMimes: ["text/toml"],
    extensions: [".toml"],
    family: "data",
    textual: true,
    icon: "i-ph-file-code",
    color: "amber",
    extraction: "text",
    thumbnail: "none",
    viewer: "code",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
  },
  {
    id: "config",
    // No registered MIME for INI-family files — stored as text/plain and
    // recognised by extension (see `extensionOnly`).
    mime: "text/plain",
    aliasMimes: [],
    extensions: [
      ".ini",
      ".cfg",
      ".conf",
      ".env",
      ".properties",
      ".editorconfig",
    ],
    family: "data",
    textual: true,
    icon: "i-ph-file-ini",
    color: "amber",
    extraction: "text",
    thumbnail: "none",
    viewer: "code",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
    extensionOnly: true,
  },

  {
    id: "ics",
    mime: "text/calendar",
    aliasMimes: ["application/ics"],
    extensions: [".ics", ".ical"],
    family: "data",
    textual: true,
    icon: "i-ph-calendar",
    color: "teal",
    extraction: "text",
    thumbnail: "none",
    // iCalendar is a line-folded key:value stream, not a table — the
    // syntax-highlighted block keeps the folding visible rather than
    // reflowing it into nonsense.
    viewer: "code",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
  },
  {
    id: "vcf",
    mime: "text/vcard",
    aliasMimes: ["text/x-vcard"],
    extensions: [".vcf", ".vcard"],
    family: "data",
    textual: true,
    icon: "i-ph-address-book",
    color: "teal",
    extraction: "text",
    thumbnail: "none",
    viewer: "code",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
  },

  // ------------------------------------------------------------------ //
  // Email — headers + body + attachment list extracted to markdown.     //
  // Attachments are LISTED here; the agent unpacks them in the sandbox. //
  // ------------------------------------------------------------------ //
  {
    id: "eml",
    mime: "message/rfc822",
    aliasMimes: ["application/mbox"],
    extensions: [".eml", ".mbox"],
    family: "email",
    textual: true,
    icon: "i-ph-envelope-simple",
    color: "teal",
    extraction: "email",
    thumbnail: "none",
    viewer: "email",
    agentAccess: "email-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "msg",
    mime: "application/vnd.ms-outlook",
    // NOT `application/x-cfb`: `file-type` reports that for every Compound
    // File Binary container (.doc / .xls / .ppt included), so it is
    // disambiguated by extension in `detect.ts`, never aliased here.
    aliasMimes: ["application/x-msg"],
    extensions: [".msg"],
    family: "email",
    textual: false,
    icon: "i-ph-envelope-simple",
    color: "teal",
    extraction: "email",
    thumbnail: "none",
    viewer: "email",
    agentAccess: "email-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },

  // ------------------------------------------------------------------ //
  // Images                                                              //
  // ------------------------------------------------------------------ //
  {
    id: "png",
    mime: "image/png",
    aliasMimes: [],
    extensions: [".png"],
    family: "image",
    textual: false,
    icon: "i-ph-file-image",
    color: "purple",
    extraction: "image-ocr",
    thumbnail: "native-image",
    viewer: "image",
    agentAccess: "image",
    surfaces: PHOTO_SURFACES,
    sidecar: "when-ocr-text",
  },
  {
    id: "jpeg",
    mime: "image/jpeg",
    aliasMimes: ["image/jpg"],
    extensions: [".jpg", ".jpeg"],
    family: "image",
    textual: false,
    icon: "i-ph-file-image",
    color: "purple",
    extraction: "image-ocr",
    thumbnail: "native-image",
    viewer: "image",
    agentAccess: "image",
    surfaces: PHOTO_SURFACES,
    sidecar: "when-ocr-text",
  },
  {
    id: "webp",
    mime: "image/webp",
    aliasMimes: [],
    extensions: [".webp"],
    family: "image",
    textual: false,
    icon: "i-ph-file-image",
    color: "purple",
    extraction: "image-ocr",
    thumbnail: "native-image",
    viewer: "image",
    agentAccess: "image",
    surfaces: PHOTO_SURFACES,
    sidecar: "when-ocr-text",
  },
  {
    id: "avif",
    mime: "image/avif",
    aliasMimes: [],
    extensions: [".avif"],
    family: "image",
    textual: false,
    icon: "i-ph-file-image",
    color: "purple",
    extraction: "image-ocr",
    // Bun's statically linked codecs stop at JPEG / PNG / WebP / GIF / BMP;
    // AVIF and HEIC decode through the OS, which a Linux container has not
    // got. Every browser we target renders it, so the preview is native and
    // only the thumbnail goes without.
    thumbnail: "none",
    viewer: "image",
    // Not `image`: the vision tool's model pool takes JPEG / PNG / GIF /
    // WebP and nothing else, so promising vision here would promise a
    // refusal. Text reaches the agent through the OCR sidecar instead.
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "when-ocr-text",
  },
  {
    id: "gif",
    mime: "image/gif",
    aliasMimes: [],
    extensions: [".gif"],
    family: "image",
    textual: false,
    icon: "i-ph-file-image",
    color: "purple",
    extraction: "image-ocr",
    thumbnail: "native-image",
    viewer: "image",
    agentAccess: "image",
    // Not an avatar source: animation would be flattened on re-encode.
    surfaces: DOC_SURFACES,
    sidecar: "when-ocr-text",
  },
  {
    id: "bmp",
    mime: "image/bmp",
    aliasMimes: ["image/x-ms-bmp"],
    extensions: [".bmp"],
    family: "image",
    textual: false,
    icon: "i-ph-file-image",
    color: "purple",
    // Mistral OCR does not list BMP among its image inputs, but
    // LibreOffice imports it — so it reaches OCR as a PDF, the same
    // detour ODT and RTF take.
    extraction: "convert-ocr",
    thumbnail: "libreoffice",
    // Browsers have decoded BMP natively for twenty years: no conversion
    // is needed for the preview, only for the reading.
    viewer: "image",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "when-ocr-text",
  },
  {
    id: "tiff",
    mime: "image/tiff",
    aliasMimes: ["image/tif", "image/x-tiff"],
    extensions: [".tiff", ".tif"],
    family: "image",
    textual: false,
    icon: "i-ph-file-image",
    color: "purple",
    // The format scanners, fax gateways and document-management systems
    // still emit, and routinely multi-page — which is why it takes the
    // document route end to end rather than the single-frame image one.
    extraction: "convert-ocr",
    thumbnail: "libreoffice",
    // No browser renders TIFF. LibreOffice does, and the resulting PDF
    // keeps every page instead of just the first frame.
    viewer: "pdf-converted",
    agentAccess: "ocr-sidecar",
    surfaces: DOC_SURFACES,
    sidecar: "always",
  },
  {
    id: "svg",
    mime: "image/svg+xml",
    aliasMimes: [],
    extensions: [".svg"],
    family: "image",
    textual: true,
    icon: "i-ph-file-svg",
    color: "purple",
    // XML markup, not a raster: read as text, never sent to OCR. Rendered
    // through `<img>` so any embedded script stays inert.
    extraction: "text",
    thumbnail: "none",
    viewer: "image",
    agentAccess: "raw-text",
    surfaces: DOC_SURFACES,
    sidecar: "never",
  },

  // ------------------------------------------------------------------ //
  // Video — no text extraction; the vision tool analyses these.         //
  // ------------------------------------------------------------------ //
  {
    id: "mp4",
    mime: "video/mp4",
    aliasMimes: [],
    extensions: [".mp4", ".m4v"],
    family: "video",
    textual: false,
    icon: "i-ph-file-video",
    color: "pink",
    extraction: "none",
    thumbnail: "none",
    viewer: "none",
    agentAccess: "opaque",
    surfaces: VIDEO_SURFACES,
    sidecar: "never",
  },
  {
    id: "webm",
    mime: "video/webm",
    aliasMimes: [],
    extensions: [".webm"],
    family: "video",
    textual: false,
    icon: "i-ph-file-video",
    color: "pink",
    extraction: "none",
    thumbnail: "none",
    viewer: "none",
    agentAccess: "opaque",
    surfaces: VIDEO_SURFACES,
    sidecar: "never",
  },
  {
    id: "quicktime",
    mime: "video/quicktime",
    aliasMimes: [],
    extensions: [".mov"],
    family: "video",
    textual: false,
    icon: "i-ph-file-video",
    color: "pink",
    extraction: "none",
    thumbnail: "none",
    viewer: "none",
    agentAccess: "opaque",
    surfaces: VIDEO_SURFACES,
    sidecar: "never",
  },
];

/**
 * Extension → Shiki language id, for the `code` viewer and fenced blocks.
 * Only extensions that also appear on the `code` / `data` defs belong
 * here; an unknown extension renders as plain text (Shiki preloads a
 * handful of grammars and falls back silently).
 */
export const CODE_LANGUAGES: Readonly<Record<string, string>> = {
  ".js": "javascript",
  ".jsx": "jsx",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".ts": "typescript",
  ".tsx": "tsx",
  ".mts": "typescript",
  ".cts": "typescript",
  ".vue": "vue",
  ".svelte": "svelte",
  ".py": "python",
  ".pyi": "python",
  ".rb": "ruby",
  ".go": "go",
  ".rs": "rust",
  ".c": "c",
  ".h": "c",
  ".cpp": "cpp",
  ".cc": "cpp",
  ".cxx": "cpp",
  ".hpp": "cpp",
  ".cs": "csharp",
  ".java": "java",
  ".kt": "kotlin",
  ".kts": "kotlin",
  ".swift": "swift",
  ".php": "php",
  ".sh": "bash",
  ".bash": "bash",
  ".zsh": "bash",
  ".fish": "fish",
  ".ps1": "powershell",
  ".sql": "sql",
  ".r": "r",
  ".lua": "lua",
  ".pl": "perl",
  ".scala": "scala",
  ".dart": "dart",
  ".ex": "elixir",
  ".exs": "elixir",
  ".erl": "erlang",
  ".hs": "haskell",
  ".clj": "clojure",
  ".css": "css",
  ".scss": "scss",
  ".less": "less",
  ".graphql": "graphql",
  ".gql": "graphql",
  ".proto": "proto",
  ".tf": "terraform",
  ".tfvars": "terraform",
  ".dockerfile": "dockerfile",
  ".ipynb": "json",
  ".diff": "diff",
  ".patch": "diff",
  ".rst": "rst",
  ".adoc": "asciidoc",
  ".asciidoc": "asciidoc",
  ".tex": "latex",
  ".json": "json",
  ".jsonc": "jsonc",
  ".json5": "json5",
  ".jsonl": "json",
  ".geojson": "json",
  ".yaml": "yaml",
  ".yml": "yaml",
  ".xml": "xml",
  ".xsd": "xml",
  ".xsl": "xml",
  ".plist": "xml",
  ".toml": "toml",
  ".ini": "ini",
  ".cfg": "ini",
  ".conf": "ini",
  ".env": "dotenv",
  ".properties": "ini",
  ".editorconfig": "ini",
  ".html": "html",
  ".htm": "html",
  ".xhtml": "html",
  ".svg": "xml",
  ".md": "markdown",
  ".markdown": "markdown",
  ".mdx": "mdx",
};

/**
 * Extensionless filenames that are nonetheless source files. Matched
 * case-insensitively on the whole basename.
 */
export const CODE_BASENAMES: Readonly<Record<string, string>> = {
  dockerfile: "dockerfile",
  makefile: "makefile",
  gemfile: "ruby",
  rakefile: "ruby",
  procfile: "bash",
  vagrantfile: "ruby",
  jenkinsfile: "groovy",
};
