import { sql } from "drizzle-orm";
import {
  type AnyPgColumn,
  boolean,
  customType,
  decimal,
  index,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { organization, team, user } from "./auth-schema";
import { collections } from "./collections";
import { documents } from "./documents";
import {
  domainEventActorEnum,
  ontologySourceEnum,
  ontologyStatusEnum,
} from "./ontology-enums";

// Postgres tsvector (Drizzle ships no native column). Maintained by the
// service layer (NOT a generated column — the expression would have to be
// IMMUTABLE and can't reference the dynamic field catalog).
const tsvector = customType<{ data: string }>({
  dataType() {
    return "tsvector";
  },
});

/**
 * Records — the REGISTRY of the unified graph: one row per record, for
 * every collection. A record is one instance of a collection: a Client row,
 * a Pricing line, a Document mirror, an AI-extracted Company.
 *
 * This table holds ONLY the cross-cutting system columns — identity (`label`,
 * `normalizedLabel`, `searchVector`), trust (`status`/`source`/`confidence`),
 * ownership (`teamId` = owning team), audit stamps, and the polymorphic id that
 * `links` / `domain_events` reference. The TYPED FIELD VALUES live in a real
 * per-type extension table `data.coll_<collectionId-hex>` (one typed column per
 * scalar field, `id` = FK back to this row), generated by the collection-schema DDL
 * engine. Centralizing system concerns here means RLS, cross-team sharing,
 * full-text search and audit are defined ONCE, not per generated table.
 *
 * Trust is separated by `status` + `source`, not a second table. No
 * record-level bi-temporal columns: a record's per-attribute history is derived
 * by folding `domain_events` (the durable journal). World-time that matters to a
 * query (a price's year, a contract date) is a normal typed field on the
 * extension table.
 */
export const collectionRecords = pgTable(
  "collection_records",
  {
    id: uuid("id")
      .default(sql`uuid_generate_v7()`)
      .primaryKey(),

    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    teamId: uuid("team_id")
      .notNull()
      .references(() => team.id, { onDelete: "cascade" }),
    // Optional private owner; NULL = team-shared.
    userId: uuid("user_id").references(() => user.id, { onDelete: "set null" }),

    collectionId: uuid("collection_id")
      .notNull()
      .references(() => collections.id, { onDelete: "cascade" }),

    // Denormalized display label (from the type's is_title field, or a built-in
    // for system types: filename for document, name for company/person).
    label: text("label").notNull(),
    // Lowercased/stripped label for trigram dedup + resolution (reuses
    // normalizeEntityName). Service-maintained.
    normalizedLabel: varchar("normalized_label", { length: 300 })
      .notNull()
      .default(""),
    // Known alternative normalized names — alias-array matching (match Stage 2).
    aliases: text("aliases")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    // BM25 full-text over label + the type's text fields. Service-maintained.
    searchVector: tsvector("search_vector"),

    // Trust / lifecycle (mirrors the proven entities model).
    status: ontologyStatusEnum("status").notNull().default("confirmed"),
    source: ontologySourceEnum("source").notNull().default("user_manual"),
    confidence: decimal("confidence", { precision: 4, scale: 3 }),
    // Provenance: the domain_events entry that produced/last-touched this row.
    // Soft reference (no FK) — domain_events is append-only and never deleted,
    // and a hard FK would create a table-creation cycle with domain_events.
    sourceEventId: uuid("source_event_id"),
    // RESERVED — merge target when two confirmed records are the same entity.
    mergedIntoId: uuid("merged_into_id").references(
      (): AnyPgColumn => collectionRecords.id,
      { onDelete: "set null" },
    ),

    // 1:1 anchor to the uploaded file for `document` records.
    documentId: uuid("document_id").references(() => documents.id, {
      onDelete: "set null",
    }),

    // Cross-team sharing mode. TRUE (default) = the record follows its TYPE's
    // audience live (a type grant makes it visible); FALSE = the record carries
    // its OWN audience via `record_shares` (always a subset of the type's), so a
    // custom record can be narrower than its type. The RLS policy gates the
    // type-grant arm on this flag — see the collection_records policy + `scope.ts`.
    inheritTypeSharing: boolean("inherit_type_sharing").notNull().default(true),

    // Denormalized actor stamps (Notion's Created-by / Last-edited-by). Cheap
    // "who touched this" display + filtering ("my records", "AI-created"); the
    // full per-attribute history still lives in `domain_events`. Populated from
    // the same `EventActor` threaded through the create/update services.
    createdByActor: domainEventActorEnum("created_by_actor"),
    createdByUserId: uuid("created_by_user_id").references(() => user.id, {
      onDelete: "set null",
    }),
    updatedByActor: domainEventActorEnum("updated_by_actor"),
    updatedByUserId: uuid("updated_by_user_id").references(() => user.id, {
      onDelete: "set null",
    }),

    createdAt: timestamp("created_at", { mode: "date", withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { mode: "date", withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index("collection_records_team_type_idx").on(
      table.teamId,
      table.collectionId,
    ),
    index("collection_records_team_type_status_idx").on(
      table.teamId,
      table.collectionId,
      table.status,
    ),
    index("collection_records_search_gin_idx").using("gin", table.searchVector),
    index("collection_records_normalized_label_idx").on(
      table.collectionId,
      table.normalizedLabel,
    ),
    index("collection_records_normalized_label_trgm_idx").using(
      "gin",
      sql`${table.normalizedLabel} gin_trgm_ops`,
    ),
    index("collection_records_aliases_gin_idx").using("gin", table.aliases),
    // 1:1 document ↔ record.
    uniqueIndex("collection_records_document_uniq")
      .on(table.documentId)
      .where(sql`document_id IS NOT NULL`),
  ],
);

export type CollectionRecord = typeof collectionRecords.$inferSelect;
export type NewCollectionRecord = typeof collectionRecords.$inferInsert;

/**
 * A registry record plus its reconstructed typed `data` — the shape the record
 * services and API return. The registry row holds system columns; `data` is
 * assembled from the per-type extension table (`data.coll_<collectionId>`) keyed by
 * field key. Services keep speaking `data` even though storage is now typed
 * columns.
 */
export type CollectionRecordWithData = CollectionRecord & {
  data: Record<string, unknown>;
};
