// Auth schema (auto-generated by Better-Auth - DO NOT MODIFY)
export * from "./auth-schema";

// Sign-up access control (closed-beta gate: allowlisted emails + domains)
export * from "./signup-access";

// Auth security audit trail (sign-in, email change, password reset, ...)
export * from "./auth-audit";

// Organization extensions (enterprise_settings, agency_settings)
export * from "./organization-extensions";

// Per-team AI model selection (chantier C8)
export * from "./team-ai-settings";

// Folders and labels (folders, labels, document_labels)
export * from "./folders";

// Documents (file storage and pre-extraction)
export * from "./documents";

// Dynamic data system (ontology) — runtime-defined object types, fields,
// relations, and governed actions. The catalog half of the unified graph.
export * from "./action-types";
export * from "./link-types";
export * from "./object-types";
export * from "./ontology-enums";

// Dynamic data system — the data plane: typed nodes (object_records), typed
// edges (links), and the durable journal (domain_events) feeding memory + audit.
export * from "./domain-events";
export * from "./links";
export * from "./object-records";

// Field definitions (per-object-type configurable fields — the field catalog)
// `field-types` is the registry: the field-type catalogue + per-type config.
export * from "./field-definitions";
export * from "./field-types";

// Metrics and logs (usage_metrics, activity_logs, webhooks)
export * from "./metrics";

// AI vectors (unified RAG vector store: documents, memories, skills, context)
export * from "./ai-vectors";

// AI (ai_conversations, ai_messages)
export * from "./ai";

// AI chat files (user-uploaded attachments on chatbot conversations)
export * from "./chat-files";

// File extractions (content-addressed OCR/extraction cache shared across
// chat files, Drive documents, and context files — keyed by org + hash)
export * from "./file-extractions";

// AI context (Projects-style user + team persistent context + files)
export * from "./ai-context";

// AI memory (agent-writable memory store — Anthropic memory_20250818-style)
export * from "./ai-memory";

// Skills (chatbot SKILL.md catalogue + per-team enable/disable overrides)
export * from "./skills";

// External apps (Nango connections + write-action approval gate)
export * from "./external-apps";
