// Auth schema (auto-generated by Better-Auth - DO NOT MODIFY)
export * from "./auth-schema";

// Sign-up access control (closed-beta gate: allowlisted emails + domains)
export * from "./signup-access";

// Auth security audit trail (sign-in, email change, password reset, ...)
export * from "./auth-audit";

// Organization extensions (enterprise_settings, agency_settings)
export * from "./organization-extensions";

// Per-team AI model selection (chantier C8)
export * from "./team-ai-settings";

// Folders (document hierarchy)
export * from "./folders";

// Documents (file storage and pre-extraction)
export * from "./documents";

// Dynamic data system (ontology) — runtime-defined object types, fields,
// relations, and governed actions. The catalog half of the unified graph.
export * from "./action-types";
export * from "./link-types";
export * from "./object-types";
export * from "./ontology-enums";

// Dynamic data system — the data plane: typed nodes (object_records), typed
// edges (links), and the durable journal (domain_events) feeding memory + audit.
export * from "./domain-events";
export * from "./links";
export * from "./object-records";

// Named journal-consumption cursors (memory sweep, future trigger engine)
export * from "./worker-cursors";

// Field definitions (per-object-type configurable fields — the field catalog)
// `field-types` is the registry: the field-type catalogue + per-type config.
export * from "./field-definitions";
export * from "./field-types";

// Global (org-agnostic) geocode cache for `location` fields.
export * from "./mapbox-geocode-cache";

// Per-team geospatial store for `location` fields (PostGIS-backed). Typed
// `location` columns FK into it; the map view + spatial filters query its geom.
export * from "./locations";

// Object sharing (cross-team ACL: object_grants = share a type, record_shares =
// share one record). Consulted by the object_records RLS predicate.
export * from "./object-sharing";

// Metrics and logs (usage_metrics, activity_logs, webhooks)
export * from "./metrics";

// AI vectors (unified RAG vector store: documents, memories, skills, context)
export * from "./ai-vectors";

// AI (ai_conversations, ai_messages)
export * from "./ai";

// AI chat files (user-uploaded attachments on chatbot conversations)
export * from "./chat-files";

// File extractions (content-addressed OCR/extraction cache shared across
// chat files, Drive documents, and context files — keyed by org + hash)
export * from "./file-extractions";

// AI context (Projects-style user + team persistent context + files)
export * from "./ai-context";

// AI memory (agent-writable memory store — Anthropic memory_20250818-style)
export * from "./ai-memory";

// AI episodes (distilled episodic memory: conversations, record activity,
// consolidation merges — vectorized into ai_vectors as source_type=episodes)
export * from "./ai-episodes";

// Skills (chatbot SKILL.md catalogue + per-team enable/disable overrides)
export * from "./skills";

// External apps (Nango connections)
export * from "./external-apps";

// Approvals (generic human-in-the-loop decision gate — external-app plans,
// record writes, questions — shared by the chatbot + the workflow executor)
export * from "./approvals";

// Workflows (autonomous agents: definitions + runs, Trigger.dev-driven)
export * from "./workflows";
